"""common/materialization.json — the shared banner fragments and imported directories (C102)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from common import jsondata, materialization
from common.project_root import aitna_root_name


def test_materialization_json_carries_the_banner_and_dirs():
    data = json.loads((Path(materialization.__file__).parent / "materialization.json").read_text(encoding="utf-8"))
    assert set(data) == {"generated_banner", "imported_dirs"}
    assert data["generated_banner"]["prefix"] == "Generated by "
    assert data["generated_banner"]["suffix"] == "/akmon/bin/sync.py. Do not edit this file by hand."
    assert data["imported_dirs"] == ["guardrails", "profiles"]


def test_the_banner_tracks_the_configured_root():
    assert materialization.generated_banner() == (
        f"Generated by {aitna_root_name()}/akmon/bin/sync.py. Do not edit this file by hand."
    )
    assert materialization.generated_marker() == "Generated by "
    assert materialization.imported_dirs() == ("guardrails", "profiles")


def test_the_loader_reads_exactly_materialization_json(monkeypatch):
    seen: list[Path] = []
    real_read = jsondata.read

    def capture(path):
        seen.append(path)
        return real_read(path)

    monkeypatch.setattr(jsondata, "read", capture)
    for loader in (materialization.generated_marker, materialization.generated_banner, materialization.imported_dirs):
        loader()
    assert seen == [Path(materialization.__file__).with_name("materialization.json")] * 3


def test_a_missing_data_file_fails_from_the_public_functions(monkeypatch):
    def broken(path):
        raise jsondata.DataFileError(f"akmon data file missing: {path}")

    monkeypatch.setattr(jsondata, "read", broken)
    for loader in (materialization.generated_marker, materialization.generated_banner):
        with pytest.raises(jsondata.DataFileError):
            loader()
