/**
 * node:test for `js/common/materialization.mjs` — the named pins of the twin: the banner under
 * the configured root, the heading rule where Python's whitespace and line breaks differ from
 * JS's, and the freshness check over a real project and tree. The full spec is
 * `meta/conformance/units/materialization.toml`, run through `probe.mjs`.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import { posix } from "node:path";

import {
  generatedBanner, generatedMarker, importedDirs, materializedDir, materializedMarkdown, materializedText,
  staleMaterialized } from "./materialization.mjs";

const data = JSON.parse(fs.readFileSync(new URL("../../common/materialization.json", import.meta.url), "utf-8"));
const BANNER = "Generated by _aitna/akmon/bin/sync.py. Do not edit this file by hand.";

/** Run `body` with `AITNA_ROOT` set as given (`null`: unset), then restored. */
function withRoot(/** @type {string | null} */ root, /** @type {() => void} */ body) {
  const saved = process.env.AITNA_ROOT;
  try {
    if (root === null) {
      delete process.env.AITNA_ROOT;
    } else {
      process.env.AITNA_ROOT = root;
    }
    body();
  } finally {
    if (saved === undefined) {
      delete process.env.AITNA_ROOT;
    } else {
      process.env.AITNA_ROOT = saved;
    }
  }
}

/** A project and a tree under a scratch directory, removed after `body`. */
function withWorld(/** @type {(project: string, tree: string, copies: string) => void} */ body) {
  const scratch = fs.mkdtempSync(posix.join(os.tmpdir(), "akmon-materialization-test-"));
  try {
    const project = posix.join(scratch, "project");
    const tree = posix.join(scratch, "tree");
    fs.mkdirSync(project);
    fs.mkdirSync(tree);
    body(project, tree, posix.join(project, "_aitna", ".akmon"));
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }
}

/** Write `text` at `relative` under `base`, making the directories. */
function put(/** @type {string} */ base, /** @type {string} */ relative, /** @type {string | Buffer} */ text) {
  fs.mkdirSync(posix.dirname(posix.join(base, relative)), { recursive: true });
  fs.writeFileSync(posix.join(base, relative), text);
}

test("the banner tracks the configured root; the recognition prefix does not", () => {
  withRoot(null, () => assert.equal(generatedBanner(data), BANNER));
  withRoot("/tools//ai/", () => assert.equal(generatedBanner(data), BANNER.replace("_aitna", "tools//ai")));
  withRoot("/", () => assert.equal(generatedBanner(data), BANNER));
  assert.equal(generatedMarker(data), "Generated by ");
  assert.deepEqual(importedDirs(data), ["guardrails", "profiles"]);
});

test("the banner follows a leading heading, keeping the heading's own line ending", () => {
  withRoot(null, () => {
    const comment = `<!-- ${BANNER} -->`;
    assert.equal(materializedMarkdown(data, "# T\nbody\n"), `# T\n${comment}\n\nbody\n`);
    assert.equal(materializedMarkdown(data, "# T\r\nbody"), `# T\r\n${comment}\n\nbody`);
    assert.equal(materializedMarkdown(data, "# T"), `# T${comment}\n\n`);
    assert.equal(materializedMarkdown(data, ""), `${comment}\n\n`);
    assert.equal(materializedMarkdown(data, "body\n# T\n"), `${comment}\n\nbody\n# T\n`);
  });
});

test("the heading rule uses Python's line breaks and Python's whitespace, not JS's", () => {
  withRoot(null, () => {
    const comment = `<!-- ${BANNER} -->`;
    const at = (/** @type {number} */ code) => String.fromCodePoint(code);
    // A line ends at these for `splitlines`; a split on "\n" would carry on to the next line.
    for (const code of [0x0b, 0x0c, 0x85, 0x2028, 0x2029]) {
      const text = `# T${at(code)}body`;
      assert.equal(materializedMarkdown(data, text), `# T${at(code)}${comment}\n\nbody`, `U+${code.toString(16)}`);
    }
    // Whitespace for `lstrip`: yes for these, which JS's `\s` lacks...
    for (const code of [0x1f, 0xa0, 0x3000]) {
      const text = `${at(code)}# T\nx`;
      assert.equal(materializedMarkdown(data, text), `${at(code)}# T\n${comment}\n\nx`, `U+${code.toString(16)}`);
    }
    // ... and no for a byte-order mark, which JS's `trim` strips.
    const bom = `${at(0xfeff)}# T\nx`;
    assert.equal(materializedMarkdown(data, bom), `${comment}\n\n${bom}`);
  });
});

test("only a name ending in .md gets the HTML-comment form", () => {
  withRoot(null, () => {
    assert.equal(materializedText(data, "ruff.toml", "x"), `# ${BANNER}\n\nx`);
    assert.equal(materializedText(data, "A.MD", "x"), `# ${BANNER}\n\nx`);
    assert.equal(materializedText(data, ".md", "x"), `<!-- ${BANNER} -->\n\nx`);
  });
});

test("the copies live under the dev layer's .akmon", () => {
  withRoot(null, () => assert.equal(materializedDir("/p"), "/p/_aitna/.akmon"));
  withRoot("tools/ai", () => assert.equal(materializedDir("/p/"), "/p/tools/ai/.akmon"));
});

test("a copy equal to what the tree would produce is current; every other answer names the file", () => {
  withRoot(null, () =>
    withWorld((project, tree, copies) => {
      put(tree, "guardrails/fresh.md", "# F\nbody\n");
      put(copies, "guardrails/fresh.md", `# F\n<!-- ${BANNER} -->\n\nbody\n`);
      put(tree, "guardrails/old.md", "# O\nnew\n");
      put(copies, "guardrails/old.md", `# O\n<!-- ${BANNER} -->\n\nold\n`);
      put(copies, "guardrails/gone.md", "x");
      put(tree, "profiles/ruff.toml", "line-length = 120\n");
      put(copies, "profiles/ruff.toml", `# ${BANNER}\n\nline-length = 120\n`);
      put(copies, "profiles/notes.txt", "not the standard's");
      assert.deepEqual(staleMaterialized(data, project, tree), ["guardrails/gone.md", "guardrails/old.md"]);
    }),
  );
});

test("a project with no materialization has nothing stale", () => {
  withRoot(null, () =>
    withWorld((project, tree) => {
      put(tree, "guardrails/a.md", "# A\n");
      assert.deepEqual(staleMaterialized(data, project, tree), []);
    }),
  );
});

test("text is compared the way Path.read_text reads it: newlines translated, BOM kept", () => {
  withRoot(null, () =>
    withWorld((project, tree, copies) => {
      put(tree, "guardrails/crlf.md", "# A\r\nbody\r\n");
      put(copies, "guardrails/crlf.md", `# A\r\n<!-- ${BANNER} -->\r\n\r\nbody\r\n`);
      put(tree, "guardrails/bom.md", "\ufeff# A\nbody\n");
      put(copies, "guardrails/bom.md", `# A\n<!-- ${BANNER} -->\n\nbody\n`);
      assert.deepEqual(staleMaterialized(data, project, tree), ["guardrails/bom.md"]);
    }),
  );
});

test("a file that is not UTF-8 raises rather than counting as stale; a missing source is checked first", () => {
  withRoot(null, () =>
    withWorld((project, tree, copies) => {
      put(copies, "guardrails/a.md", Buffer.from([0xff, 0xfe, 0x41]));
      assert.deepEqual(staleMaterialized(data, project, tree), ["guardrails/a.md"]);
      put(tree, "guardrails/a.md", "# A\n");
      assert.throws(() => staleMaterialized(data, project, tree), TypeError);
    }),
  );
});

test("a copy or source that is a directory, or unreadable, is stale", () => {
  withRoot(null, () =>
    withWorld((project, tree, copies) => {
      fs.mkdirSync(posix.join(copies, "guardrails", "x.md"), { recursive: true });
      put(tree, "guardrails/x.md", "# X\n");
      put(copies, "guardrails/y.md", "y");
      fs.mkdirSync(posix.join(tree, "guardrails", "y.md"), { recursive: true });
      assert.deepEqual(staleMaterialized(data, project, tree), ["guardrails/x.md", "guardrails/y.md"]);
    }),
  );
});

test("an unreadable copy is stale and an unlistable directory is silent", { skip: process.getuid?.() === 0 }, () => {
  withRoot(null, () =>
    withWorld((project, tree, copies) => {
      put(tree, "guardrails/a.md", "# A\n");
      put(copies, "guardrails/a.md", `# A\n<!-- ${BANNER} -->\n\n`);
      fs.chmodSync(posix.join(copies, "guardrails", "a.md"), 0o000);
      try {
        assert.deepEqual(staleMaterialized(data, project, tree), ["guardrails/a.md"]);
      } finally {
        fs.chmodSync(posix.join(copies, "guardrails", "a.md"), 0o600);
      }
      fs.chmodSync(posix.join(copies, "guardrails"), 0o000);
      try {
        assert.deepEqual(staleMaterialized(data, project, tree), []);
      } finally {
        fs.chmodSync(posix.join(copies, "guardrails"), 0o700);
      }
    }),
  );
});
