"""Model-routing core: registry loading, tier binding, generated-agent content.

Pure logic shared by the init tool (``init.py``) and the SessionStart hook
(``hooks/model-routing.py``). Stdlib-only; no I/O beyond reading the registry and the
optional project overlay. Vocabulary and policy: MODEL.md § Capability tiers; the
registry (``registry.json``) is the single owner of semantic selection policy +
task-kind data.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shlex
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

_AITNA_ROOT_DEFAULT = "_aitna"

# Committed, per-project overlay (same shape as the registry, deep-merged over it; may add
# a "briefs" map with per-agent markdown appended to the generated subagent bodies).
OVERLAY_NAME = "model-routing.json"
# Per-user resolved binding (gitignored, like .env) — written by init, read by the hook.
LOCAL_CONFIG_REL = ".claude/model-routing.local.json"
DELEGATION_LOG_REL = ".claude/model-routing.log"
AGENTS_DIR_REL = ".claude/agents"

GENERATED_BANNER = (
    "Generated by akmon tools/model_routing/init.py from registry.json — "
    "edit the registry or the project overlay, not this file."
)


def aitna_root_name() -> str:
    """The configured dev-layer root, as a project-root-relative POSIX path (default ``_aitna``)."""
    return (os.environ.get("AITNA_ROOT") or _AITNA_ROOT_DEFAULT).strip("/") or _AITNA_ROOT_DEFAULT


def registry_path(akmon_dir: Path) -> Path:
    return akmon_dir / "tools" / "model_routing" / "registry.json"


def overlay_path(project_root: Path) -> Path:
    return project_root / aitna_root_name() / OVERLAY_NAME


def _deep_merge(base: dict, override: dict) -> dict:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_registry(akmon_dir: Path, project_root: Path | None = None) -> dict:
    """The merged registry: akmon data deep-merged with the project overlay (if any)."""
    registry = json.loads(registry_path(akmon_dir).read_text(encoding="utf-8"))
    if project_root is not None:
        overlay = overlay_path(project_root)
        if overlay.is_file():
            registry = _deep_merge(registry, json.loads(overlay.read_text(encoding="utf-8")))
    return registry


def registry_hash(registry: dict) -> str:
    """Stable digest of the merged registry — staleness detection for the local config."""
    canonical = json.dumps(registry, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


@dataclass(frozen=True)
class Binding:
    """The tier→model binding — a pure function of (selection policy, orchestrator, available)."""

    vendor: str
    orchestrator: str
    reasoner: str
    worker: str
    mid: str
    auditor: str
    escalation: tuple[str, ...]
    semantic_fallback: bool = False
    warning: str | None = None
    second_opinion_cli: str | None = None


def _semantic_rungs(vendor_data: dict) -> list[str]:
    fallback = vendor_data.get("semantic_fallback", {})
    worker = str(fallback.get("worker") or "worker")
    mid = str(fallback.get("mid") or "mid")
    reasoner = str(fallback.get("reasoner") or "strongest")
    auditor = str(fallback.get("auditor") or "strongest")
    rungs: list[str] = []
    for rung in (worker, mid, reasoner):
        if rung not in rungs:
            rungs.append(rung)
    if auditor not in rungs:
        rungs.append(auditor)
    return rungs


def compute_binding(
    registry: dict,
    orchestrator: str,
    available: list[str] | None = None,
    vendor: str = "anthropic",
) -> Binding:
    """Bind tiers to model aliases from a semantic vendor policy (MODEL.md § Capability tiers).

    ``available`` is the concrete, local, discovery-derived ladder ordered weakest → strongest.
    The shared registry stores only the selection policy. Without ``available`` the binding uses
    semantic fallback labels and carries a warning; generated file-backed agents then omit concrete
    model frontmatter instead of pretending those labels are valid vendor model ids.
    """
    vendor_data = registry[vendor]
    semantic = not available
    rungs = list(available) if available else _semantic_rungs(vendor_data)
    if not rungs:
        rungs = _semantic_rungs(vendor_data)

    auditor = rungs[-1]  # pinned max, always — unlike the now-dynamic reasoner
    worker = rungs[0]
    worker_pos = rungs.index(worker)
    mid = rungs[min(worker_pos + 1, len(rungs) - 1)]
    escalation = tuple(rungs[worker_pos + 1 : len(rungs) - 1])

    policy = vendor_data.get("selection_policy", {})
    reasoner_policy = policy.get("reasoner", "highest")
    if semantic:
        fallback = vendor_data.get("semantic_fallback", {})
        reasoner = str(fallback.get("reasoner") or "strongest")
    elif reasoner_policy == "orchestrator" and orchestrator in rungs:
        reasoner = orchestrator
    else:
        # Unknown orchestrator, or a non-"orchestrator" policy value (e.g. "highest") —
        # fall back to the top rung.
        reasoner = rungs[-1]

    warning = None
    if semantic:
        warning = (
            "using semantic model labels because no concrete model list was provided; "
            "run model discovery or pass --available to bind vendor aliases locally"
        )
    else:
        floor = policy.get("orchestrator_floor", "highest")
        floor_rung = rungs[-1] if floor == "highest" else str(floor)
        if orchestrator not in rungs:
            warning = (
                f"orchestrator '{orchestrator}' is not in the discovered model list — "
                "cannot rank it against the floor; refresh discovery or check the alias"
            )
        elif floor_rung in rungs:
            # Healthy corridor: floor ≤ orchestrator < top (design §3, ADR 0006). When the
            # ladder tops out at the floor, floor == top and both arms stay silent — the
            # accepted degraded mode. A floor alias absent from the ladder disables the
            # check (nothing to rank against); the relative "highest" floor resolves to the
            # top rung, reproducing the pre-corridor below-top warning.
            orch_rank, floor_rank = rungs.index(orchestrator), rungs.index(floor_rung)
            if orch_rank < floor_rank:
                warning = (
                    f"orchestrator={orchestrator} is below the orchestration floor ({floor_rung}) — "
                    "decomposition/synthesis degrade everything downstream; consider /model up. "
                    "Advisory: the auditor's level verdict is the authoritative check"
                )
            elif orch_rank == len(rungs) - 1 and floor_rank < len(rungs) - 1:
                warning = (
                    f"orchestrator={orchestrator} runs on the auditor's reserved top rung — "
                    f"orchestration does not need it; consider /model down to {floor_rung}"
                )

    provider = opposite_vendor(registry, vendor)
    second_opinion = registry.get(provider, {}).get("second_opinion", {})
    return Binding(
        vendor=vendor,
        orchestrator=orchestrator,
        reasoner=reasoner,
        worker=worker,
        mid=mid,
        auditor=auditor,
        escalation=escalation,
        semantic_fallback=semantic,
        warning=warning,
        second_opinion_cli=second_opinion.get("cli"),
    )


def task_kind_floors(registry: dict, rungs: list[str]) -> dict[str, str]:
    """Per-task-kind rung floors, resolved to concrete aliases from ``rungs``.

    Only task kinds carrying a ``"floor"`` key are included. ``"highest"`` resolves to
    ``rungs[-1]``; a literal alias passes through only when present in ``rungs``. A kind
    whose floor cannot be resolved (empty ``rungs``, or an alias absent from it) is skipped.
    """
    floors: dict[str, str] = {}
    if not rungs:
        return floors
    for kind, spec in registry.get("task_kinds", {}).items():
        floor = spec.get("floor")
        if not floor:
            continue
        if floor == "highest":
            floors[kind] = rungs[-1]
        elif floor in rungs:
            floors[kind] = str(floor)
    return floors


def vendors_with_routing_policy(registry: dict) -> list[str]:
    """Vendors that can run a main/orchestrator session under the semantic routing policy."""
    return [
        name
        for name, spec in registry.items()
        if isinstance(spec, dict) and isinstance(spec.get("selection_policy"), dict)
    ]


def opposite_vendor(registry: dict, vendor: str) -> str:
    """Default second-opinion provider: another configured vendor, preferring the recorded order."""
    for candidate in vendors_with_routing_policy(registry):
        if candidate != vendor and second_opinion_spec(registry, candidate, required=False):
            return candidate
    return vendor


def second_opinion_provider(registry: dict, config: dict, orchestrator_vendor: str) -> str:
    """Resolve the external review provider from config or the vendor-opposite default."""
    configured = config.get("second_opinion_provider") if isinstance(config, dict) else None
    if isinstance(configured, str) and configured:
        return configured
    return opposite_vendor(registry, orchestrator_vendor)


def second_opinion_spec(registry: dict, provider: str, *, required: bool = True) -> dict:
    spec = registry.get(provider, {}).get("second_opinion", {})
    if isinstance(spec, dict) and spec.get("invoke") and spec.get("report_dir"):
        return spec
    if required:
        raise KeyError(f"second-opinion provider '{provider}' has no usable invoke/report_dir spec")
    return {}


def second_opinion_fallback_model(rungs: list[str], orchestrator: str, auditor: str) -> str | None:
    """The same-vendor fallback rung when no other vendor is reachable (design §9.7 #2).

    The diversity requirement is about *model* priors, not vendor branding: the strongest
    rung that differs from both the orchestrator (the author) and the auditor. ``None`` when
    no rung differs from the orchestrator at all (a single distinct rung) — the caller warns
    or skips; it must never fall back to the same model.
    """
    for rung in reversed(rungs):
        if rung != orchestrator and rung != auditor:
            return rung
    return None


def second_opinion_command(spec: dict, prompt: str, model: str | None = None) -> list[str]:
    """Build the non-interactive CLI command; the prompt is passed as the final argv.

    When ``model`` is given and the spec declares a ``model_flag`` format string
    (e.g. ``"--model {model}"``), the flag is inserted before the prompt so the
    same-vendor branch of the diversity ladder can pin a *different* model.
    """
    invoke = str(spec["invoke"])
    argv = shlex.split(invoke)
    if model:
        model_flag = spec.get("model_flag")
        if model_flag:
            argv += shlex.split(str(model_flag).format(model=model))
    return [*argv, prompt]


@dataclass(frozen=True)
class SecondOpinionTarget:
    provider: str
    model: str | None  # None = the provider CLI's default model (other-vendor case)


def resolve_second_opinion(
    registry: dict, config: dict, orchestrator_vendor: str
) -> SecondOpinionTarget | None:
    """Walk `second_opinion_policy.diversity_ladder` to a (provider, model) target.

    Diversity is about *model priors* (design §9.3 item 3): the reviewer must differ
    from the models it reviews. Ladder steps (registry data):
      - "other-vendor": another configured vendor with a usable spec — different priors
        by construction, so model=None (its CLI default is already a different model);
      - "same-vendor-other-model": the same vendor, pinned to the strongest rung that
        differs from BOTH orchestrator (author) and auditor, via
        `second_opinion_fallback_model` (design §9.7 #2);
      - `never: same-model` — if no rung differs, return None (skip); the caller must
        never fall back to the same model.

    An explicit `config["second_opinion_provider"]` is honored: a configured *other*
    vendor satisfies the other-vendor step; configured == orchestrator vendor routes to
    the same-vendor branch.
    """
    policy = registry.get("second_opinion_policy", {}) if isinstance(registry, dict) else {}
    ladder = policy.get("diversity_ladder") or ["other-vendor", "same-vendor-other-model"]
    orchestrator = str(config.get("orchestrator") or "")
    auditor = str(config.get("binding", {}).get("auditor") or "")
    configured = config.get("second_opinion_provider")
    for step in ladder:
        if step == "other-vendor":
            # An explicit same-vendor override is a deliberate "stay on my vendor, pin a
            # different model" choice — skip the other-vendor step so it falls through to
            # same-vendor-other-model rather than silently picking the opposite vendor.
            if isinstance(configured, str) and configured == orchestrator_vendor:
                continue
            provider = (
                configured
                if isinstance(configured, str) and configured and configured != orchestrator_vendor
                else opposite_vendor(registry, orchestrator_vendor)
            )
            if provider != orchestrator_vendor and second_opinion_spec(registry, provider, required=False):
                return SecondOpinionTarget(provider, None)
        elif step == "same-vendor-other-model":
            provider = orchestrator_vendor
            if not second_opinion_spec(registry, provider, required=False):
                continue
            model = config.get("second_opinion_fallback_model")
            if not model:
                rungs = config.get("available") or _semantic_rungs(registry.get(provider, {}))
                model = second_opinion_fallback_model(rungs, orchestrator, auditor)
            if model:
                return SecondOpinionTarget(provider, str(model))
    return None


# --------------------------------------------------------------------------------------
# Generated subagent definitions (the `k-` akmon namespace)
# --------------------------------------------------------------------------------------

# Each agent groups the task kinds whose briefs coincide; the tier picks its model from
# the binding. Bodies are project-neutral (this is SHARED); project specifics are appended
# via the overlay's "briefs" map.
@dataclass(frozen=True)
class AgentSpec:
    name: str
    tier: str  # "worker" | "mid" | "reasoner" | "auditor"
    description: str
    tools: str | None  # frontmatter `tools:`; None = all tools
    body: str
    kinds: tuple[str, ...] = field(default=())


AGENT_SPECS: tuple[AgentSpec, ...] = (
    AgentSpec(
        name="k-explorer",
        tier="worker",
        kinds=("explore-search", "summarize"),
        description=(
            "Worker tier — task kinds `explore-search` and `summarize`. Use for read-only "
            "fan-out: find where something lives in code/docs, sweep many files, condense "
            "files/logs/docs into a brief. Returns conclusions, not file dumps."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **explorer** delegate: read-only reconnaissance for the orchestrating session.

- Answer the question you were given; do not expand scope.
- Return **conclusions with `file:line` references**, not raw file contents. Keep the
  report short enough to be pasted into another agent's context.
- Verify against the actual code/docs you read — never answer from memory of similar
  projects.
- Never edit anything; you have no write tools by design. Bash is for **read-only
  inspection only** — `git log/diff/show/status`, `ls`, `jq` over local files; never run
  a command that mutates files, state, or history.
- **Escalation signal:** if the question is ambiguous, the evidence is contradictory, or
  the answer requires a judgment call beyond locating facts — say so explicitly in one
  short paragraph instead of guessing. The orchestrator escalates on that signal.""",
    ),
    AgentSpec(
        name="k-mechanic",
        tier="worker",
        kinds=("mech-edit", "test-scaffold", "doc-sync"),
        description=(
            "Worker tier — task kinds `mech-edit`, `test-scaffold`, `doc-sync`. Use for "
            "mechanical, behaviour-preserving work from an explicit spec: renames, sweeps, "
            "formatting, moving code without reshaping it, test skeletons/fixtures from a "
            "stated spec, propagating an already-decided fact across docs."
        ),
        tools=None,
        body="""You are the **mechanic** delegate: mechanical realization of an explicit spec.

- Execute the spec exactly; the decisions are already made — you make none. Match the
  surrounding code's naming, idiom, and comment density.
- Behaviour-preserving means behaviour-preserving: no drive-by refactors, no "while I'm
  here" improvements, no unrelated edits.
- Follow the project's guardrails (AGENTS.md): its import conventions, its command
  runner; artifacts (comments, docs) in English.
- Run the checks the spec names (the project's lint/test commands) and report their real
  output. Never `git add`/`commit`/`push` — the owner owns commits.
- **Escalation signal:** if the spec is ambiguous, incomplete, or executing it would
  require a decision (an interface reshape, a naming convention, a contract change) —
  stop and return a short report saying exactly what is undecided. Do not improvise.""",
    ),
    AgentSpec(
        name="k-validator",
        tier="worker",
        kinds=("validate-loop",),
        description=(
            "Worker tier — task kind `validate-loop`. Use to drive project gates to green: "
            "run tests/lint/verification tools, parse the output, apply minimal mechanical "
            "fixes, re-run until green — or stop with a diagnosis when the failure is not "
            "mechanical."
        ),
        tools=None,
        body="""You are the **validator** delegate: the run → parse → fix → re-run loop.

- Gates you run (as instructed by the task): the project's test and lint commands
  (AGENTS.md names them), and akmon's `bin/verify.py --strict` / `bin/sync.py --check`
  when named.
- **Fix scope is strictly mechanical:** missing/stale imports, autofixable lint,
  formatting, wrong paths/names after a rename, a test asserting a message that
  trivially changed. Apply the smallest fix that makes the gate pass, re-run, repeat.
- **Never touch** math, data shapes, contracts, or architecture — that is owner-verify
  territory: stop and report instead. Never weaken a test to make it pass; never delete
  or skip a failing test. Never `git add`/`commit`/`push`.
- Report at the end: gates run, final status per gate, fixes applied (file:line), and —
  for anything you did not fix — the failure evidence and your one-paragraph diagnosis.
- **Escalation signal:** two re-runs without progress, or any fix that would exceed the
  mechanical scope — stop and return the diagnosis; the orchestrator escalates.""",
    ),
    AgentSpec(
        name="k-implementer",
        tier="mid",
        kinds=("implement-under-spec",),
        description=(
            "Worker tier, mid rung — task kind `implement-under-spec`. Use to write code "
            "against a decided contract/design: the signatures, data shapes, and structure "
            "are already fixed; no open design decisions remain. Ships the change with its "
            "tests."
        ),
        tools=None,
        body="""You are the **implementer** delegate: realize a decided design in code.

- Implement exactly the stated contract (signatures, data shapes, placement). Reuse the
  project's abstractions (AGENTS.md names the load-bearing ones) — extend them, don't
  fork them.
- A behaviour change ships with a test; tests mirror the source layout. Run the project's
  test and lint commands (targeted first, then as instructed); report real output,
  including failures.
- Follow the language guardrails: type hints on public surfaces, every callable reads as
  `f(subject, *rest)` — subject first. Artifacts in English.
- Never `git add`/`commit`/`push` — the owner owns commits. Changes to math or data
  shape are owner-verified — flag them explicitly in your report.
- **Escalation signal:** if a load-bearing decision *emerges mid-build* (a new
  convention, an interface reshape, a contract change) — **stop**, per code-flow: report
  the gap instead of deciding it. Same if the given contract contradicts the code you
  find.""",
    ),
    AgentSpec(
        name="k-reasoner",
        tier="reasoner",
        kinds=("debug-deep", "design-fork", "quant-derivation", "plan-draft"),
        description=(
            "Reasoner tier — task kinds `debug-deep`, `design-fork`, `quant-derivation`, "
            "`plan-draft`. Use for load-bearing thinking: multi-cause/cross-boundary "
            "failure analysis, drafting options for a contested design fork, deriving "
            "pricing/quant math, drafting a decomposition/zone plan for the orchestrator. "
            "Returns a structured report; it drafts, it never decides or edits."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **reasoner** delegate: load-bearing analysis and drafting for the
orchestrating session. You produce a report — you do not edit files, and your output is
a draft for the owner's verification, never a decision.

- **debug-deep:** read the code, reproduce with read-only commands (the project's test
  runner), and return: the failure mechanism, the evidence chain (`file:line`), candidate
  causes ranked, and the minimal fix criteria — not the fix itself unless asked.
- **design-fork:** frame the design space — realistic options including the status quo,
  evaluation criteria, trade-offs, risks, revisit-if conditions. Recommend one; never
  present a single option as inevitable.
- **quant-derivation:** derive step by step, state assumptions and domain boundaries;
  respect the project's numeric conventions (quant profile). Every formula is explicitly
  flagged for owner verification — plausibility is not agreement.
- **plan-draft:** draft the work decomposition — the zone plan (named zones/modules the
  fan-out splits by), risks, ordering, and what would prove the plan wrong. A draft for
  the orchestrator to adopt or reject — never route or spawn work yourself.
- Verify names, signatures, and paths in the actual code before reasoning from them.
- **Escalation signal:** if the question cannot be answered without information only the
  owner has (intent, priorities, external constraints), return the precise question to
  ask rather than an assumption dressed as analysis.""",
    ),
    AgentSpec(
        name="k-auditor",
        tier="auditor",
        kinds=("audit",),
        description=(
            "Auditor tier — task kind `audit`. Clean-context audit of a "
            "whole gate's collected material (a gate-pack): contradictions between "
            "independently-correct findings, uncovered seams between zones, re-ranking "
            "deltas, a level verdict. Pinned to the maximal available model; drafts and "
            "audits, never edits."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **auditor** delegate: a clean-context audit of a gate's whole
collected material — the first check on the orchestrator's own synthesis.

- You receive a **gate-pack** (artifacts + the Frame-stage yardstick + a coverage map)
  and nothing else — no session history. The clean context is the mechanism: judge
  against the stated yardstick, not one inferred from the findings in front of you.
- Output exactly these sections:
  - **Contradictions** — between independently-correct findings/options.
  - **Uncovered seams** — derived from the coverage map: zones no worker checked,
    boundaries between zones.
  - **Re-ranking / recommendation deltas.**
  - **Level verdict** — does the material suggest the task exceeded the session-model
    hypothesis; if so, name the specific piece to redo on a higher rung, or recommend
    `/model` up.
  - **Could not verify** — an explicit list.
- Bash is for **read-only inspection only** (e.g. grep-derived dependency edges) — never
  a command that mutates files, state, or history.
- Your report is advisory — the orchestrator and owner decide; you never edit.
- **Escalation signal:** if the pack lacks what the audit needs (no coverage map, no
  yardstick), return the precise gap instead of a diluted verdict.""",
    ),
)


def _agent_model(spec: AgentSpec, binding: Binding) -> str | None:
    if binding.semantic_fallback:
        return None
    return {
        "worker": binding.worker,
        "mid": binding.mid,
        "reasoner": binding.reasoner,
        "auditor": binding.auditor,
    }[spec.tier]


def agent_file_content(spec: AgentSpec, binding: Binding, brief_extra: str = "") -> str:
    lines = ["---", f"name: {spec.name}", "description: >-"]
    lines.extend(f"  {chunk}" for chunk in _wrap(spec.description, 88))
    if spec.tools:
        lines.append(f"tools: {spec.tools}")
    model = _agent_model(spec, binding)
    if model:
        lines.append(f"model: {model}")
    lines.append("---")
    lines.append("")
    lines.append(f"<!-- {GENERATED_BANNER} -->")
    lines.append("")
    lines.append(spec.body)
    if brief_extra.strip():
        lines.append("")
        lines.append("<!-- project overlay brief -->")
        lines.append("")
        lines.append(brief_extra.strip())
    return "\n".join(lines) + "\n"


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    chunks: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            chunks.append(current)
            current = word
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks


def generated_agent_files(registry: dict, binding: Binding) -> dict[str, str]:
    """Map of ``.claude/agents/<name>.md`` relative paths → generated content."""
    briefs = registry.get("briefs", {})
    return {
        f"{AGENTS_DIR_REL}/{spec.name}.md": agent_file_content(spec, binding, briefs.get(spec.name, ""))
        for spec in AGENT_SPECS
    }


_AGENT_BY_NAME: dict[str, AgentSpec] = {spec.name: spec for spec in AGENT_SPECS}


def subagent_kinds(name: str) -> tuple[str, ...]:
    """Task kinds a generated subagent covers; empty for a host built-in / unknown name."""
    spec = _AGENT_BY_NAME.get(name)
    return spec.kinds if spec else ()


def bound_model_for(config: dict, subagent_type: str) -> str | None:
    """Model a generated ``k-*`` agent is pinned to — its tier's binding alias, or None.

    The generated agent frontmatter carries ``model: <alias>`` (see ``_agent_model``), but an
    ``Agent`` call rarely echoes it — so the delegation record shows ``-`` and the console
    line omits the model. Deriving it from the recorded binding restores it. None for an
    unknown agent (a host built-in) or a semantic-fallback binding whose tier value is not a
    real alias (mirrors ``_agent_model`` emitting no ``model:`` line in that mode).
    """
    spec = _AGENT_BY_NAME.get(subagent_type)
    if spec is None or not isinstance(config, dict):
        return None
    binding = config.get("binding")
    if not isinstance(binding, dict):
        return None
    model = binding.get(spec.tier)
    if not model:
        return None
    available = config.get("available") or []
    if available and model not in available:
        return None
    return str(model)


_ROLE_DECL_RE = re.compile(r"🧭\s*agent:\s*([A-Za-z][\w-]*)")


def _assistant_text(entry: dict) -> str:
    message = entry.get("message")
    if not isinstance(message, dict):
        return ""
    content = message.get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(
            block.get("text", "")
            for block in content
            if isinstance(block, dict) and block.get("type") == "text"
        )
    return ""


def active_role(transcript_path: str | Path | None) -> str | None:
    """The role the orchestrator last declared (``🧭 agent: <name>``), read from the transcript.

    The chat declaration is invisible to a hook as chat, but the transcript records it in the
    assistant turns a hook can already scan (as C22/C23 do). Only main-chain assistant turns
    are read, so the SessionStart reminder / a subagent echo never masquerades as the
    declaration. Returns the last-declared name (the caller maps it to a role row), else None.
    """
    if not transcript_path:
        return None
    path = Path(transcript_path)
    if not path.is_file():
        return None
    role: str | None = None
    try:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                # Cheap ascii pre-filter: the emoji may be \u-escaped in the JSONL, but
                # "agent:" is always literal. json.loads then decodes the real marker.
                if "agent:" not in line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(entry, dict) or entry.get("type") != "assistant" or entry.get("isSidechain"):
                    continue
                for match in _ROLE_DECL_RE.finditer(_assistant_text(entry)):
                    role = match.group(1)
    except OSError:
        return None
    return role


def role_matrix_warning(registry: dict, subagent_type: str, role: str | None) -> str | None:
    """Advisory (§10.2): the routed agent has no task kind the active role may route.

    Subagent granularity — the call carries the agent, not the specific kind — so warn only
    when *none* of the agent's kinds intersect the role's allowed row. That catches an edit
    agent routed under the analysis-only ``review`` role without false-flagging a multi-kind
    agent (e.g. ``k-reasoner``) that shares one legitimate kind. None when the role is
    unknown/undeclared or the agent is a host built-in (no kinds).

    **Cross-cutting verification kinds** (``cross_cutting_kinds`` — ``independent-review`` and
    ``audit``) are *not* role-gated (A7 (b), §10.2): any role may route them and *when* they
    apply is the structural trigger (§9.5), not the producing role. They join every role's
    allowed set, so an agent whose only kinds are cross-cutting (e.g. ``k-auditor``) never
    warns under any role.
    """
    if not role:
        return None
    allowed = registry.get("role_task_kinds", {}).get(role)
    if not allowed:
        return None
    allowed = set(allowed) | set(registry.get("cross_cutting_kinds", []))
    kinds = subagent_kinds(subagent_type)
    if not kinds or set(kinds) & allowed:
        return None
    return (
        f"role/task-kind: {subagent_type} ({', '.join(kinds)}) is outside the active role "
        f"'{role}' — it routes {', '.join(allowed)}. Re-route or switch role."
    )


# --------------------------------------------------------------------------------------
# Local config + status line (the SessionStart hook contract)
# --------------------------------------------------------------------------------------


def resolve_alias(model_id: str | None, available: list[str] | None) -> str | None:
    """Map a concrete vendor model id (e.g. ``claude-opus-4-8``) to a known local alias.

    The alias is matched as a case-insensitive substring of the id, preferring the longest
    match so overlapping aliases disambiguate (``opus`` over a bare ``o``). ``None`` when no
    alias in ``available`` matches — the caller keeps the recorded binding rather than guess.
    """
    if not model_id or not available:
        return None
    lowered = model_id.lower()
    matches = [alias for alias in available if alias and alias.lower() in lowered]
    return max(matches, key=len) if matches else None


def _last_main_turn(transcript_path: str | Path | None) -> tuple[str | None, dict | None]:
    """(model id, usage) of the last *main-chain* assistant turn in the session transcript.

    The transcript (a JSONL the harness records; its path arrives in the hook payload)
    carries ``message.model`` and ``message.usage`` per assistant turn. Sidechain
    (subagent) turns and synthetic entries are skipped, so a delegate's model or usage
    never masquerades as the orchestrator's. One pass yields both facts — orchestrator
    detection and context-pressure detection share it. ``(None, None)`` when the
    transcript is missing/empty/unreadable or names no model yet.
    """
    if not transcript_path:
        return None, None
    path = Path(transcript_path)
    if not path.is_file():
        return None, None
    model_id: str | None = None
    usage: dict | None = None
    try:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if '"model"' not in line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(entry, dict) or entry.get("type") != "assistant" or entry.get("isSidechain"):
                    continue
                message = entry.get("message")
                model = message.get("model") if isinstance(message, dict) else None
                if isinstance(model, str) and model and not model.startswith("<"):
                    model_id = model
                    entry_usage = message.get("usage")
                    usage = entry_usage if isinstance(entry_usage, dict) else None
    except OSError:
        return None, None
    return model_id, usage


def detect_orchestrator(transcript_path: str | Path | None, available: list[str] | None) -> str | None:
    """Alias of the model the *main chain* last ran on, read from the session transcript.

    ``None`` when the transcript names no model yet or the model maps to no known alias
    (a fresh session before the first turn, or an unrecognized id): the caller then keeps
    the recorded orchestrator instead of guessing.
    """
    model_id, _ = _last_main_turn(transcript_path)
    return resolve_alias(model_id, available)


# --------------------------------------------------------------------------------------
# Context-pressure detection (design §12, ADR 0006) — the tokens axis of runtime weakness
# --------------------------------------------------------------------------------------


def context_fill(usage: dict | None) -> int | None:
    """Context-window fill at a turn: the three input components partition the prompt.

    ``output_tokens`` is not context carried forward, so it is excluded. ``None`` when the
    usage carries no input component at all — the caller stays silent rather than warn
    from a guess.
    """
    if not isinstance(usage, dict):
        return None
    components = [
        usage.get(key)
        for key in ("input_tokens", "cache_read_input_tokens", "cache_creation_input_tokens")
    ]
    if not any(isinstance(value, int) for value in components):
        return None
    return sum(value for value in components if isinstance(value, int))


def context_window(registry: dict, model_id: str | None) -> int:
    """The model's context window: an alias-substring exception from ``windows``, else the default."""
    policy = registry.get("context_pressure", {})
    default = int(policy.get("window_default") or 200000)
    windows = policy.get("windows", {})
    if model_id and isinstance(windows, dict):
        lowered = model_id.lower()
        matches = [key for key in windows if key and key.lower() in lowered]
        if matches:
            return int(windows[max(matches, key=len)])
    return default


def _context_fill_metrics(
    registry: dict, transcript_path: str | Path | None
) -> tuple[int, int, float] | None:
    """``(fill, window, ratio)`` for the last main-chain turn; ``None`` if unavailable.

    Shared by ``context_pressure_notice`` (banded warnings) and ``context_fill_ratio``
    (the C29 axis-2 coefficient) so both read the same fill/window definition.
    """
    model_id, usage = _last_main_turn(transcript_path)
    fill = context_fill(usage)
    if fill is None:
        return None
    window = context_window(registry, model_id)
    if window <= 0:
        return None
    return fill, window, fill / window


def context_fill_ratio(registry: dict, transcript_path: str | Path | None) -> float | None:
    """Context-window fill ratio (0..~1+) for the last main-chain turn; ``None`` if unavailable.

    Reused by the C29 output-weight nudge to weight cumulative tool-output bytes by how
    full the window already is — the same signal ``context_pressure_notice`` bands.
    """
    metrics = _context_fill_metrics(registry, transcript_path)
    return metrics[2] if metrics else None


def context_pressure_notice(
    registry: dict,
    transcript_path: str | Path | None,
    session_id: str | None,
    *,
    marker_dir: Path | None = None,
) -> list[str]:
    """Warning lines when the context fill crossed a *new* warn band; ``[]`` otherwise.

    Banded and throttled (the delegation-nudge marker idiom): a per-session temp-dir
    marker records the last announced band, so only a band *rise* warns — 0→high once,
    high→critical once more, a steady fill stays silent. A fill dropping below the lowest
    band (a compaction landed) clears the marker, so each compaction cycle gets its own
    warnings. Missing/malformed usage → silent; never raises past I/O.
    """
    policy = registry.get("context_pressure", {})
    ratios = [float(r) for r in policy.get("warn_ratios") or [] if isinstance(r, (int, float))]
    if not ratios:
        return []
    metrics = _context_fill_metrics(registry, transcript_path)
    if metrics is None:
        return []
    fill, window, ratio = metrics
    band: int | None = None
    for index, threshold in enumerate(ratios):
        if ratio >= threshold:
            band = index

    marker = (marker_dir or Path(tempfile.gettempdir())) / f"akmon-context-pressure-{session_id or 'nosession'}"
    try:
        last_band: int | None = int(marker.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        last_band = None

    if band is None:
        # Below every band — a compaction (or a fresh session) resets the throttle.
        try:
            marker.unlink(missing_ok=True)
        except OSError:
            pass
        return []
    if last_band is not None and band <= last_band:
        return []
    try:
        marker.write_text(str(band), encoding="utf-8")
    except OSError:
        pass

    critical = band == len(ratios) - 1 and len(ratios) > 1
    advice = (
        "critical — compact now (/compact) or finish the current unit of work first"
        if critical
        else "checkpoint durable state (files/TASKS) and plan compaction"
    )
    return [f"⚠ context pressure: ~{ratio:.0%} of {window // 1000}k ({fill} tokens) — {advice}"]


def binding_artifacts(
    registry: dict, binding: Binding, *, second_opinion: bool, available: list[str] | None
) -> dict[str, str]:
    """Every generated routing artifact as ``project-root-relative path → content``.

    The generated ``k-*`` subagent definitions plus the local config — the single set the
    init tool and the SessionStart/UserPromptSubmit hook both write, so a rebind from
    either path produces byte-identical files.
    """
    files = dict(generated_agent_files(registry, binding))
    config = local_config(binding, registry, second_opinion=second_opinion, available=available)
    files[LOCAL_CONFIG_REL] = json.dumps(config, indent=2) + "\n"
    return files


def write_artifacts(root: Path, files: dict[str, str], *, write: bool = True) -> list[Path]:
    """Write each artifact whose content changed; return the changed paths (idempotent)."""
    changed: list[Path] = []
    for rel, content in files.items():
        path = root / rel
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        changed.append(path)
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return changed


def rebind_to(
    root: Path, registry: dict, config: dict, orchestrator: str, *, write: bool = True
) -> tuple[Binding, list[Path]]:
    """Recompute the binding for ``orchestrator`` and (re)write the artifacts under ``root``.

    Reuses the recorded ``available`` list and opt-ins from ``config`` — only the
    orchestrator moves. Idempotent: unchanged files are left untouched. This is how the
    hook makes subagent models follow the session's actual orchestrating model.
    """
    available = config.get("available")
    second_opinion = bool(config.get("second_opinion"))
    vendor = str(config.get("vendor") or "anthropic")
    binding = compute_binding(registry, orchestrator, available, vendor)
    files = binding_artifacts(registry, binding, second_opinion=second_opinion, available=available)
    return binding, write_artifacts(root, files, write=write)


def local_config(binding: Binding, registry: dict, *, second_opinion: bool, available: list[str] | None) -> dict:
    config = {
        "vendor": binding.vendor,
        "orchestrator": binding.orchestrator,
        "binding": {
            "reasoner": binding.reasoner,
            "worker": binding.worker,
            "mid": binding.mid,
            "auditor": binding.auditor,
            "escalation": list(binding.escalation),
        },
        "second_opinion": second_opinion,
        "second_opinion_provider": opposite_vendor(registry, binding.vendor),
        "available": available,
        "registry_hash": registry_hash(registry),
        "task_kind_floors": task_kind_floors(registry, available or []),
    }
    provider = config["second_opinion_provider"]
    if provider == binding.vendor:
        rungs = list(available) if available else _semantic_rungs(registry.get(binding.vendor, {}))
        config["second_opinion_fallback_model"] = second_opinion_fallback_model(
            rungs, binding.orchestrator, binding.auditor
        )
    return config


def staleness(config: dict, registry: dict, settings_model: str | None) -> str | None:
    """Why the local config is stale — or None when it is fresh."""
    if not config:
        return "no local config — model routing is not initialized"
    if config.get("registry_hash") != registry_hash(registry):
        return "registry (or project overlay) changed since init"
    if settings_model and settings_model != config.get("orchestrator"):
        return f"settings default model '{settings_model}' differs from configured orchestrator"
    return None


def status_lines(config: dict, registry: dict, aitna: str) -> list[str]:
    """The steady-state status injection: one binding line + self-check, plus any warning."""
    binding = config.get("binding", {})
    second = "on" if config.get("second_opinion") else "off"
    orchestrator_vendor = str(config.get("vendor") or "anthropic")
    provider = second_opinion_provider(registry, config, orchestrator_vendor)
    second_cli = registry.get(provider, {}).get("second_opinion", {}).get("cli", "-")
    orchestrator = config.get("orchestrator", "?")
    lines = [
        "[akmon] model routing: "
        f"vendor={orchestrator_vendor} · orchestrator={orchestrator} · reasoner={binding.get('reasoner', '?')} · "
        f"auditor={binding.get('auditor', '?')} · "
        f"worker={binding.get('worker', '?')} · mid={binding.get('mid', '?')} · "
        f"second-opinion={second_cli}({second})",
        "Delegation is the default — route by task kind (MODEL.md § Capability tiers): "
        "k-explorer/k-mechanic/k-validator (worker) · k-implementer (mid) · k-reasoner · "
        "k-auditor (audit at gates); escalate one rung only on failure signals.",
        f"Self-check: if your actual model is not '{orchestrator}', re-run "
        f"`python3 {aitna}/akmon/tools/model_routing/init.py --orchestrator <alias>`.",
    ]
    warning = compute_binding(registry, orchestrator, config.get("available"), orchestrator_vendor).warning
    if warning:
        lines.append(f"⚠ {warning}")
    return lines


def rebind_notice(config: dict, registry: dict) -> list[str]:
    """The concise mid-session note after the orchestrator model changed (UserPromptSubmit).

    One line naming the new orchestrator and the recomputed subagent binding, plus the
    weak-orchestrator warning when it applies — that warning is exactly what the owner
    wants surfaced on a switch *down* to a thin model.
    """
    binding = config.get("binding", {})
    orchestrator = config.get("orchestrator", "?")
    vendor = str(config.get("vendor") or "anthropic")
    lines = [
        f"[akmon] orchestrator model changed → {orchestrator}; subagent binding updated: "
        f"reasoner={binding.get('reasoner', '?')} · auditor={binding.get('auditor', '?')} · "
        f"worker={binding.get('worker', '?')} · mid={binding.get('mid', '?')}. "
        "Regenerated k-* agents follow the new model.",
    ]
    warning = compute_binding(registry, orchestrator, config.get("available"), vendor).warning
    if warning:
        lines.append(f"⚠ {warning}")
    return lines


def init_instruction(reason: str, aitna: str) -> list[str]:
    return [
        f"[akmon] Model routing needs initialization — {reason}.",
        "State the model you are running on and the models available in this harness, then run: "
        f"`python3 {aitna}/akmon/tools/model_routing/init.py --orchestrator <your-alias> "
        "[--available <alias,...>] [--second-opinion on|off]`.",
        "Then ask the owner to (a) confirm the proposed tier→model binding and "
        "(b) enable or decline second-opinion review, and re-run the tool with their answers.",
    ]


# --------------------------------------------------------------------------------------
# Delegation log (the PreToolUse hook contract)
# --------------------------------------------------------------------------------------

_SUBAGENT_TOOLS = frozenset({"Task", "Agent"})


ZONE_MARKER_PREFIX = "[zone:"


def parse_zone(description: str) -> tuple[str | None, str]:
    """Split a leading ``[zone:LABEL]`` marker off a delegation description.

    The zone label rides in the description — the only free-form field a subagent call
    carries (§9.4/§10.3). A marker only counts at the very start:
    ``[zone:auth] check tokens`` -> ``("auth", "check tokens")``. No marker ->
    ``(None, <description stripped>)``.
    """
    text = description.strip()
    if text.startswith(ZONE_MARKER_PREFIX):
        end = text.find("]")
        if end != -1:
            label = text[len(ZONE_MARKER_PREFIX) : end].strip()
            rest = text[end + 1 :].strip()
            return (label or None, rest)
    return (None, text)


def delegation_log_line(
    tool_name: str,
    tool_input: dict,
    timestamp: str,
    session_id: str | None = None,
    bound_model: str | None = None,
) -> str | None:
    """One TSV line per subagent delegation; None for any other tool.

    Columns: ``timestamp · session_id · subagent · model · zone · description``. The zone
    is parsed off a leading ``[zone:LABEL]`` marker in the description (removed from the
    stored description); ``-`` marks an absent session / model / zone. The model is the
    call's explicit override if given, else ``bound_model`` (the agent's pinned tier model,
    derived by the caller so the record + console line name the actual model). ``session_id``
    scopes a fan-out round for the coverage-map assembler (C17).
    """
    if tool_name not in _SUBAGENT_TOOLS:
        return None
    subagent = str(tool_input.get("subagent_type") or "-")
    model = str(tool_input.get("model") or bound_model or "-")
    raw_description = " ".join(str(tool_input.get("description") or "").split())
    zone, description = parse_zone(raw_description)
    return f"{timestamp}\t{session_id or '-'}\t{subagent}\t{model}\t{zone or '-'}\t{description}"


@dataclass(frozen=True)
class DelegationEntry:
    """One parsed delegation-log row (schema: see ``delegation_log_line``)."""

    timestamp: str
    session_id: str | None
    subagent: str
    model: str | None
    zone: str | None
    description: str


def _dash_to_none(value: str) -> str | None:
    value = value.strip()
    return None if value in ("", "-") else value


def parse_delegation_entries(lines: Iterable[str]) -> list[DelegationEntry]:
    """Parse delegation-log lines into entries.

    Handles the current 6-column schema and the legacy 4-column one (no session/zone) so
    a mixed local log still parses; lines with fewer than 4 fields are skipped.
    """
    entries: list[DelegationEntry] = []
    for raw in lines:
        line = raw.rstrip("\n")
        if not line:
            continue
        parts = line.split("\t")
        if len(parts) >= 6:
            ts, sid, subagent, model, zone = parts[0], parts[1], parts[2], parts[3], parts[4]
            description = "\t".join(parts[5:])
        elif len(parts) >= 4:
            # Legacy: timestamp · subagent · model · description (no session / zone).
            ts, sid, subagent, model, zone = parts[0], "-", parts[1], parts[2], "-"
            description = "\t".join(parts[3:])
        else:
            continue
        entries.append(
            DelegationEntry(
                timestamp=ts,
                session_id=_dash_to_none(sid),
                subagent=subagent.strip(),
                model=_dash_to_none(model),
                zone=_dash_to_none(zone),
                description=description.strip(),
            )
        )
    return entries
