"""Model-routing core: registry loading, tier binding, generated-agent content.

Pure logic shared by the init tool (``init.py``) and the SessionStart hook
(``hooks/model-routing.py``). Stdlib-only; no I/O beyond reading the registry and the
optional project overlay. Vocabulary and policy: MODEL.md § Capability tiers; the
registry (``registry.json``) is the single owner of semantic selection policy +
task-kind data.
"""

from __future__ import annotations

import hashlib
import json
import os
import shlex
from dataclasses import dataclass, field
from pathlib import Path

_FORGE_ROOT_DEFAULT = "_forge"

# Committed, per-project overlay (same shape as the registry, deep-merged over it; may add
# a "briefs" map with per-agent markdown appended to the generated subagent bodies).
OVERLAY_NAME = "model-routing.json"
# Per-user resolved binding (gitignored, like .env) — written by init, read by the hook.
LOCAL_CONFIG_REL = ".claude/model-routing.local.json"
DELEGATION_LOG_REL = ".claude/model-routing.log"
AGENTS_DIR_REL = ".claude/agents"

GENERATED_BANNER = (
    "Generated by keystone tools/model_routing/init.py from registry.json — "
    "edit the registry or the project overlay, not this file."
)


def forge_root_name() -> str:
    """The configured dev-layer root, as a project-root-relative POSIX path (default ``_forge``)."""
    return (os.environ.get("FORGE_ROOT") or _FORGE_ROOT_DEFAULT).strip("/") or _FORGE_ROOT_DEFAULT


def registry_path(keystone_dir: Path) -> Path:
    return keystone_dir / "tools" / "model_routing" / "registry.json"


def overlay_path(project_root: Path) -> Path:
    return project_root / forge_root_name() / OVERLAY_NAME


def _deep_merge(base: dict, override: dict) -> dict:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_registry(keystone_dir: Path, project_root: Path | None = None) -> dict:
    """The merged registry: keystone data deep-merged with the project overlay (if any)."""
    registry = json.loads(registry_path(keystone_dir).read_text(encoding="utf-8"))
    if project_root is not None:
        overlay = overlay_path(project_root)
        if overlay.is_file():
            registry = _deep_merge(registry, json.loads(overlay.read_text(encoding="utf-8")))
    return registry


def registry_hash(registry: dict) -> str:
    """Stable digest of the merged registry — staleness detection for the local config."""
    canonical = json.dumps(registry, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


@dataclass(frozen=True)
class Binding:
    """The tier→model binding — a pure function of (selection policy, orchestrator, available)."""

    vendor: str
    orchestrator: str
    reasoner: str
    worker: str
    mid: str
    synthesizer: str
    escalation: tuple[str, ...]
    semantic_fallback: bool = False
    warning: str | None = None
    second_opinion_cli: str | None = None


def _semantic_rungs(vendor_data: dict) -> list[str]:
    fallback = vendor_data.get("semantic_fallback", {})
    worker = str(fallback.get("worker") or "worker")
    mid = str(fallback.get("mid") or "mid")
    reasoner = str(fallback.get("reasoner") or "strongest")
    synthesizer = str(fallback.get("synthesizer") or "strongest")
    rungs: list[str] = []
    for rung in (worker, mid, reasoner):
        if rung not in rungs:
            rungs.append(rung)
    if synthesizer not in rungs:
        rungs.append(synthesizer)
    return rungs


def compute_binding(
    registry: dict,
    orchestrator: str,
    available: list[str] | None = None,
    vendor: str = "anthropic",
) -> Binding:
    """Bind tiers to model aliases from a semantic vendor policy (MODEL.md § Capability tiers).

    ``available`` is the concrete, local, discovery-derived ladder ordered weakest → strongest.
    The shared registry stores only the selection policy. Without ``available`` the binding uses
    semantic fallback labels and carries a warning; generated file-backed agents then omit concrete
    model frontmatter instead of pretending those labels are valid vendor model ids.
    """
    vendor_data = registry[vendor]
    semantic = not available
    rungs = list(available) if available else _semantic_rungs(vendor_data)
    if not rungs:
        rungs = _semantic_rungs(vendor_data)

    synthesizer = rungs[-1]  # pinned max, always — unlike the now-dynamic reasoner
    worker = rungs[0]
    worker_pos = rungs.index(worker)
    mid = rungs[min(worker_pos + 1, len(rungs) - 1)]
    escalation = tuple(rungs[worker_pos + 1 : len(rungs) - 1])

    policy = vendor_data.get("selection_policy", {})
    reasoner_policy = policy.get("reasoner", "highest")
    if semantic:
        fallback = vendor_data.get("semantic_fallback", {})
        reasoner = str(fallback.get("reasoner") or "strongest")
    elif reasoner_policy == "orchestrator" and orchestrator in rungs:
        reasoner = orchestrator
    else:
        # Unknown orchestrator, or a non-"orchestrator" policy value (e.g. "highest") —
        # fall back to the top rung.
        reasoner = rungs[-1]

    warning = None
    if semantic:
        warning = (
            "using semantic model labels because no concrete model list was provided; "
            "run model discovery or pass --available to bind vendor aliases locally"
        )
    else:
        floor = policy.get("orchestrator_floor", "highest")
        floor_rung = rungs[-1] if floor == "highest" else str(floor)
        if orchestrator not in rungs:
            warning = (
                f"orchestrator '{orchestrator}' is not in the discovered model list — "
                "cannot rank it against the floor; refresh discovery or check the alias"
            )
        elif floor_rung in rungs and rungs.index(orchestrator) < rungs.index(floor_rung):
            warning = (
                f"orchestrator={orchestrator} is below the top rung ({floor_rung}) — a weak "
                "prior only: acceptable for review/architect-dominant sessions with the "
                "synthesizer gate on; the synthesizer's level verdict is the authoritative check"
            )

    provider = opposite_vendor(registry, vendor)
    second_opinion = registry.get(provider, {}).get("second_opinion", {})
    return Binding(
        vendor=vendor,
        orchestrator=orchestrator,
        reasoner=reasoner,
        worker=worker,
        mid=mid,
        synthesizer=synthesizer,
        escalation=escalation,
        semantic_fallback=semantic,
        warning=warning,
        second_opinion_cli=second_opinion.get("cli"),
    )


def task_kind_floors(registry: dict, rungs: list[str]) -> dict[str, str]:
    """Per-task-kind rung floors, resolved to concrete aliases from ``rungs``.

    Only task kinds carrying a ``"floor"`` key are included. ``"highest"`` resolves to
    ``rungs[-1]``; a literal alias passes through only when present in ``rungs``. A kind
    whose floor cannot be resolved (empty ``rungs``, or an alias absent from it) is skipped.
    """
    floors: dict[str, str] = {}
    if not rungs:
        return floors
    for kind, spec in registry.get("task_kinds", {}).items():
        floor = spec.get("floor")
        if not floor:
            continue
        if floor == "highest":
            floors[kind] = rungs[-1]
        elif floor in rungs:
            floors[kind] = str(floor)
    return floors


def vendors_with_routing_policy(registry: dict) -> list[str]:
    """Vendors that can run a main/orchestrator session under the semantic routing policy."""
    return [
        name
        for name, spec in registry.items()
        if isinstance(spec, dict) and isinstance(spec.get("selection_policy"), dict)
    ]


def opposite_vendor(registry: dict, vendor: str) -> str:
    """Default second-opinion provider: another configured vendor, preferring the recorded order."""
    for candidate in vendors_with_routing_policy(registry):
        if candidate != vendor and second_opinion_spec(registry, candidate, required=False):
            return candidate
    return vendor


def second_opinion_provider(registry: dict, config: dict, orchestrator_vendor: str) -> str:
    """Resolve the external review provider from config or the vendor-opposite default."""
    configured = config.get("second_opinion_provider") if isinstance(config, dict) else None
    if isinstance(configured, str) and configured:
        return configured
    return opposite_vendor(registry, orchestrator_vendor)


def second_opinion_spec(registry: dict, provider: str, *, required: bool = True) -> dict:
    spec = registry.get(provider, {}).get("second_opinion", {})
    if isinstance(spec, dict) and spec.get("invoke") and spec.get("report_dir"):
        return spec
    if required:
        raise KeyError(f"second-opinion provider '{provider}' has no usable invoke/report_dir spec")
    return {}


def second_opinion_fallback_model(rungs: list[str], orchestrator: str, synthesizer: str) -> str | None:
    """The same-vendor fallback rung when no other vendor is reachable (design §9.7 #2).

    The diversity requirement is about *model* priors, not vendor branding: the strongest
    rung that differs from both the orchestrator (the author) and the synthesizer (the
    auditor). ``None`` when no rung differs from the orchestrator at all (a single distinct
    rung) — the caller warns or skips; it must never fall back to the same model.
    """
    for rung in reversed(rungs):
        if rung != orchestrator and rung != synthesizer:
            return rung
    return None


def second_opinion_command(spec: dict, prompt: str) -> list[str]:
    """Build the non-interactive CLI command; the prompt is passed as the final argv."""
    invoke = str(spec["invoke"])
    return [*shlex.split(invoke), prompt]


# --------------------------------------------------------------------------------------
# Generated subagent definitions (the `k-` keystone namespace)
# --------------------------------------------------------------------------------------

# Each agent groups the task kinds whose briefs coincide; the tier picks its model from
# the binding. Bodies are project-neutral (this is SHARED); project specifics are appended
# via the overlay's "briefs" map.
@dataclass(frozen=True)
class AgentSpec:
    name: str
    tier: str  # "worker" | "mid" | "reasoner" | "synthesizer"
    description: str
    tools: str | None  # frontmatter `tools:`; None = all tools
    body: str
    kinds: tuple[str, ...] = field(default=())


AGENT_SPECS: tuple[AgentSpec, ...] = (
    AgentSpec(
        name="k-explorer",
        tier="worker",
        kinds=("explore-search", "summarize"),
        description=(
            "Worker tier — task kinds `explore-search` and `summarize`. Use for read-only "
            "fan-out: find where something lives in code/docs, sweep many files, condense "
            "files/logs/docs into a brief. Returns conclusions, not file dumps."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **explorer** delegate: read-only reconnaissance for the orchestrating session.

- Answer the question you were given; do not expand scope.
- Return **conclusions with `file:line` references**, not raw file contents. Keep the
  report short enough to be pasted into another agent's context.
- Verify against the actual code/docs you read — never answer from memory of similar
  projects.
- Never edit anything; you have no write tools by design. Bash is for **read-only
  inspection only** — `git log/diff/show/status`, `ls`, `jq` over local files; never run
  a command that mutates files, state, or history.
- **Escalation signal:** if the question is ambiguous, the evidence is contradictory, or
  the answer requires a judgment call beyond locating facts — say so explicitly in one
  short paragraph instead of guessing. The orchestrator escalates on that signal.""",
    ),
    AgentSpec(
        name="k-mechanic",
        tier="worker",
        kinds=("mech-edit", "test-scaffold", "doc-sync"),
        description=(
            "Worker tier — task kinds `mech-edit`, `test-scaffold`, `doc-sync`. Use for "
            "mechanical, behaviour-preserving work from an explicit spec: renames, sweeps, "
            "formatting, moving code without reshaping it, test skeletons/fixtures from a "
            "stated spec, propagating an already-decided fact across docs."
        ),
        tools=None,
        body="""You are the **mechanic** delegate: mechanical realization of an explicit spec.

- Execute the spec exactly; the decisions are already made — you make none. Match the
  surrounding code's naming, idiom, and comment density.
- Behaviour-preserving means behaviour-preserving: no drive-by refactors, no "while I'm
  here" improvements, no unrelated edits.
- Follow the project's guardrails (AGENTS.md): its import conventions, its command
  runner; artifacts (comments, docs) in English.
- Run the checks the spec names (the project's lint/test commands) and report their real
  output. Never `git add`/`commit`/`push` — the owner owns commits.
- **Escalation signal:** if the spec is ambiguous, incomplete, or executing it would
  require a decision (an interface reshape, a naming convention, a contract change) —
  stop and return a short report saying exactly what is undecided. Do not improvise.""",
    ),
    AgentSpec(
        name="k-validator",
        tier="worker",
        kinds=("validate-loop",),
        description=(
            "Worker tier — task kind `validate-loop`. Use to drive project gates to green: "
            "run tests/lint/verification tools, parse the output, apply minimal mechanical "
            "fixes, re-run until green — or stop with a diagnosis when the failure is not "
            "mechanical."
        ),
        tools=None,
        body="""You are the **validator** delegate: the run → parse → fix → re-run loop.

- Gates you run (as instructed by the task): the project's test and lint commands
  (AGENTS.md names them), and keystone's `bin/verify.py --strict` / `bin/sync.py --check`
  when named.
- **Fix scope is strictly mechanical:** missing/stale imports, autofixable lint,
  formatting, wrong paths/names after a rename, a test asserting a message that
  trivially changed. Apply the smallest fix that makes the gate pass, re-run, repeat.
- **Never touch** math, data shapes, contracts, or architecture — that is owner-verify
  territory: stop and report instead. Never weaken a test to make it pass; never delete
  or skip a failing test. Never `git add`/`commit`/`push`.
- Report at the end: gates run, final status per gate, fixes applied (file:line), and —
  for anything you did not fix — the failure evidence and your one-paragraph diagnosis.
- **Escalation signal:** two re-runs without progress, or any fix that would exceed the
  mechanical scope — stop and return the diagnosis; the orchestrator escalates.""",
    ),
    AgentSpec(
        name="k-implementer",
        tier="mid",
        kinds=("implement-under-spec",),
        description=(
            "Worker tier, mid rung — task kind `implement-under-spec`. Use to write code "
            "against a decided contract/design: the signatures, data shapes, and structure "
            "are already fixed; no open design decisions remain. Ships the change with its "
            "tests."
        ),
        tools=None,
        body="""You are the **implementer** delegate: realize a decided design in code.

- Implement exactly the stated contract (signatures, data shapes, placement). Reuse the
  project's abstractions (AGENTS.md names the load-bearing ones) — extend them, don't
  fork them.
- A behaviour change ships with a test; tests mirror the source layout. Run the project's
  test and lint commands (targeted first, then as instructed); report real output,
  including failures.
- Follow the language guardrails: type hints on public surfaces, every callable reads as
  `f(subject, *rest)` — subject first. Artifacts in English.
- Never `git add`/`commit`/`push` — the owner owns commits. Changes to math or data
  shape are owner-verified — flag them explicitly in your report.
- **Escalation signal:** if a load-bearing decision *emerges mid-build* (a new
  convention, an interface reshape, a contract change) — **stop**, per code-flow: report
  the gap instead of deciding it. Same if the given contract contradicts the code you
  find.""",
    ),
    AgentSpec(
        name="k-reasoner",
        tier="reasoner",
        kinds=("debug-deep", "design-fork", "quant-derivation", "plan-draft"),
        description=(
            "Reasoner tier — task kinds `debug-deep`, `design-fork`, `quant-derivation`, "
            "`plan-draft`. Use for load-bearing thinking: multi-cause/cross-boundary "
            "failure analysis, drafting options for a contested design fork, deriving "
            "pricing/quant math, drafting a decomposition/zone plan for the orchestrator. "
            "Returns a structured report; it drafts, it never decides or edits."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **reasoner** delegate: load-bearing analysis and drafting for the
orchestrating session. You produce a report — you do not edit files, and your output is
a draft for the owner's verification, never a decision.

- **debug-deep:** read the code, reproduce with read-only commands (the project's test
  runner), and return: the failure mechanism, the evidence chain (`file:line`), candidate
  causes ranked, and the minimal fix criteria — not the fix itself unless asked.
- **design-fork:** frame the design space — realistic options including the status quo,
  evaluation criteria, trade-offs, risks, revisit-if conditions. Recommend one; never
  present a single option as inevitable.
- **quant-derivation:** derive step by step, state assumptions and domain boundaries;
  respect the project's numeric conventions (quant profile). Every formula is explicitly
  flagged for owner verification — plausibility is not agreement.
- **plan-draft:** draft the work decomposition — the zone plan (named zones/modules the
  fan-out splits by), risks, ordering, and what would prove the plan wrong. A draft for
  the orchestrator to adopt or reject — never route or spawn work yourself.
- Verify names, signatures, and paths in the actual code before reasoning from them.
- **Escalation signal:** if the question cannot be answered without information only the
  owner has (intent, priorities, external constraints), return the precise question to
  ask rather than an assumption dressed as analysis.""",
    ),
    AgentSpec(
        name="k-synthesizer",
        tier="synthesizer",
        kinds=("synthesis-verify",),
        description=(
            "Synthesizer tier — task kind `synthesis-verify`. Clean-context audit of a "
            "whole gate's collected material (a gate-pack): contradictions between "
            "independently-correct findings, uncovered seams between zones, re-ranking "
            "deltas, a level verdict. Pinned to the maximal available model; drafts and "
            "audits, never edits."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **synthesizer** delegate: a clean-context audit of a gate's whole
collected material — the first check on the orchestrator's own synthesis.

- You receive a **gate-pack** (artifacts + the Frame-stage yardstick + a coverage map)
  and nothing else — no session history. The clean context is the mechanism: judge
  against the stated yardstick, not one inferred from the findings in front of you.
- Output exactly these sections:
  - **Contradictions** — between independently-correct findings/options.
  - **Uncovered seams** — derived from the coverage map: zones no worker checked,
    boundaries between zones.
  - **Re-ranking / recommendation deltas.**
  - **Level verdict** — does the material suggest the task exceeded the session-model
    hypothesis; if so, name the specific piece to redo on a higher rung, or recommend
    `/model` up.
  - **Could not verify** — an explicit list.
- Bash is for **read-only inspection only** (e.g. grep-derived dependency edges) — never
  a command that mutates files, state, or history.
- Your report is advisory — the orchestrator and owner decide; you never edit.
- **Escalation signal:** if the pack lacks what the audit needs (no coverage map, no
  yardstick), return the precise gap instead of a diluted verdict.""",
    ),
)


def _agent_model(spec: AgentSpec, binding: Binding) -> str | None:
    if binding.semantic_fallback:
        return None
    return {
        "worker": binding.worker,
        "mid": binding.mid,
        "reasoner": binding.reasoner,
        "synthesizer": binding.synthesizer,
    }[spec.tier]


def agent_file_content(spec: AgentSpec, binding: Binding, brief_extra: str = "") -> str:
    lines = ["---", f"name: {spec.name}", "description: >-"]
    lines.extend(f"  {chunk}" for chunk in _wrap(spec.description, 88))
    if spec.tools:
        lines.append(f"tools: {spec.tools}")
    model = _agent_model(spec, binding)
    if model:
        lines.append(f"model: {model}")
    lines.append("---")
    lines.append("")
    lines.append(f"<!-- {GENERATED_BANNER} -->")
    lines.append("")
    lines.append(spec.body)
    if brief_extra.strip():
        lines.append("")
        lines.append("<!-- project overlay brief -->")
        lines.append("")
        lines.append(brief_extra.strip())
    return "\n".join(lines) + "\n"


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    chunks: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            chunks.append(current)
            current = word
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks


def generated_agent_files(registry: dict, binding: Binding) -> dict[str, str]:
    """Map of ``.claude/agents/<name>.md`` relative paths → generated content."""
    briefs = registry.get("briefs", {})
    return {
        f"{AGENTS_DIR_REL}/{spec.name}.md": agent_file_content(spec, binding, briefs.get(spec.name, ""))
        for spec in AGENT_SPECS
    }


# --------------------------------------------------------------------------------------
# Local config + status line (the SessionStart hook contract)
# --------------------------------------------------------------------------------------


def local_config(binding: Binding, registry: dict, *, second_opinion: bool, available: list[str] | None) -> dict:
    config = {
        "vendor": binding.vendor,
        "orchestrator": binding.orchestrator,
        "binding": {
            "reasoner": binding.reasoner,
            "worker": binding.worker,
            "mid": binding.mid,
            "synthesizer": binding.synthesizer,
            "escalation": list(binding.escalation),
        },
        "second_opinion": second_opinion,
        "second_opinion_provider": opposite_vendor(registry, binding.vendor),
        "available": available,
        "registry_hash": registry_hash(registry),
        "task_kind_floors": task_kind_floors(registry, available or []),
    }
    provider = config["second_opinion_provider"]
    if provider == binding.vendor:
        rungs = list(available) if available else _semantic_rungs(registry.get(binding.vendor, {}))
        config["second_opinion_fallback_model"] = second_opinion_fallback_model(
            rungs, binding.orchestrator, binding.synthesizer
        )
    return config


def staleness(config: dict, registry: dict, settings_model: str | None) -> str | None:
    """Why the local config is stale — or None when it is fresh."""
    if not config:
        return "no local config — model routing is not initialized"
    if config.get("registry_hash") != registry_hash(registry):
        return "registry (or project overlay) changed since init"
    if settings_model and settings_model != config.get("orchestrator"):
        return f"settings default model '{settings_model}' differs from configured orchestrator"
    return None


def status_lines(config: dict, registry: dict, forge: str) -> list[str]:
    """The steady-state status injection: one binding line + self-check, plus any warning."""
    binding = config.get("binding", {})
    second = "on" if config.get("second_opinion") else "off"
    orchestrator_vendor = str(config.get("vendor") or "anthropic")
    provider = second_opinion_provider(registry, config, orchestrator_vendor)
    second_cli = registry.get(provider, {}).get("second_opinion", {}).get("cli", "-")
    orchestrator = config.get("orchestrator", "?")
    lines = [
        "[keystone] model routing: "
        f"vendor={orchestrator_vendor} · orchestrator={orchestrator} · reasoner={binding.get('reasoner', '?')} · "
        f"synthesizer={binding.get('synthesizer', '?')} · "
        f"worker={binding.get('worker', '?')} · mid={binding.get('mid', '?')} · "
        f"second-opinion={second_cli}({second})",
        "Delegation is the default — route by task kind (MODEL.md § Capability tiers): "
        "k-explorer/k-mechanic/k-validator (worker) · k-implementer (mid) · k-reasoner · "
        "k-synthesizer (synthesis-verify at gates); escalate one rung only on failure signals.",
        f"Self-check: if your actual model is not '{orchestrator}', re-run "
        f"`python3 {forge}/keystone/tools/model_routing/init.py --orchestrator <alias>`.",
    ]
    warning = compute_binding(registry, orchestrator, config.get("available"), orchestrator_vendor).warning
    if warning:
        lines.append(f"⚠ {warning}")
    return lines


def init_instruction(reason: str, forge: str) -> list[str]:
    return [
        f"[keystone] Model routing needs initialization — {reason}.",
        "State the model you are running on and the models available in this harness, then run: "
        f"`python3 {forge}/keystone/tools/model_routing/init.py --orchestrator <your-alias> "
        "[--available <alias,...>] [--second-opinion on|off]`.",
        "Then ask the owner to (a) confirm the proposed tier→model binding and "
        "(b) enable or decline second-opinion review, and re-run the tool with their answers.",
    ]


# --------------------------------------------------------------------------------------
# Delegation log (the PreToolUse hook contract)
# --------------------------------------------------------------------------------------

_SUBAGENT_TOOLS = frozenset({"Task", "Agent"})


def delegation_log_line(tool_name: str, tool_input: dict, timestamp: str) -> str | None:
    """One TSV line per subagent delegation; None for any other tool."""
    if tool_name not in _SUBAGENT_TOOLS:
        return None
    subagent = str(tool_input.get("subagent_type") or "-")
    model = str(tool_input.get("model") or "-")
    description = " ".join(str(tool_input.get("description") or "").split())
    return f"{timestamp}\t{subagent}\t{model}\t{description}"
