"""Model-routing core: registry loading, tier binding, generated-agent content.

Pure logic shared by the init tool (``init.py``) and the SessionStart hook
(``hooks/model-routing.py``). Stdlib-only; no I/O beyond reading the registry and the
optional project overlay. Vocabulary and policy: MODEL.md § Capability tiers; the
registry (``registry.json``) is the single owner of semantic selection policy +
task-kind data.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import re
import shlex
import sys
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

# The optional-harness command map lives in the standard tree's ``bin/`` (C57, §7). Two parents
# up from ``tools/model_routing/`` is that tree root in every mount mode — the mounted
# ``<AITNA_ROOT>/akmon/`` and the materialized ``<AITNA_ROOT>/.akmon/`` alike — so this resolves
# without reading the mount record and stays clear of the tree-resolution fork (C69).
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from common.project_root import aitna_root_name
from common.runtime import harness_command

# Committed, per-project overlay (same shape as the registry, deep-merged over it; may add
# a "briefs" map with per-agent markdown appended to the generated subagent bodies — keyed
# by agent name, matched notation-insensitively, unmatched key is an error: see
# `resolve_briefs`).
OVERLAY_NAME = "model-routing.json"
# Per-user resolved binding (gitignored, like .env) — written by init, read by the hook.
LOCAL_CONFIG_REL = ".claude/model-routing.local.json"
DELEGATION_LOG_REL = ".claude/model-routing.log"
AGENTS_DIR_REL = ".claude/agents"

GENERATED_BANNER = (
    "Generated by akmon tools/model_routing/init.py from registry.json — "
    "edit the registry or the project overlay, not this file."
)


def registry_path(akmon_dir: Path) -> Path:
    """Path to the shipped ``registry.json`` under an akmon tree."""
    return akmon_dir / "tools" / "model_routing" / "registry.json"


def overlay_path(project_root: Path) -> Path:
    """Path to the project's committed model-routing overlay file, if any."""
    return project_root / aitna_root_name() / OVERLAY_NAME


def _deep_merge(base: dict, override: dict) -> dict:
    merged = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_registry(akmon_dir: Path, project_root: Path | None = None) -> dict:
    """The merged registry: akmon data deep-merged with the project overlay (if any)."""
    registry = json.loads(registry_path(akmon_dir).read_text(encoding="utf-8"))
    if project_root is not None:
        overlay = overlay_path(project_root)
        if overlay.is_file():
            registry = _deep_merge(registry, json.loads(overlay.read_text(encoding="utf-8")))
    return registry


def registry_hash(registry: dict) -> str:
    """Stable digest of the merged registry — staleness detection for the local config."""
    canonical = json.dumps(registry, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


@dataclass(frozen=True)
class Binding:
    """The tier→model binding — a pure function of (selection policy, orchestrator, available)."""

    vendor: str
    orchestrator: str
    reasoner: str
    worker: str
    mid: str
    auditor: str
    escalation: tuple[str, ...]
    semantic_fallback: bool = False
    warning: str | None = None
    second_opinion_cli: str | None = None


def _semantic_rungs(vendor_data: dict) -> list[str]:
    fallback = vendor_data.get("semantic_fallback", {})
    worker = str(fallback.get("worker") or "worker")
    mid = str(fallback.get("mid") or "mid")
    reasoner = str(fallback.get("reasoner") or "strongest")
    auditor = str(fallback.get("auditor") or "strongest")
    rungs: list[str] = []
    for rung in (worker, mid, reasoner):
        if rung not in rungs:
            rungs.append(rung)
    if auditor not in rungs:
        rungs.append(auditor)
    return rungs


def compute_binding(
    registry: dict,
    orchestrator: str,
    available: list[str] | None = None,
    vendor: str = "anthropic",
) -> Binding:
    """Bind tiers to model aliases from a semantic vendor policy (MODEL.md § Capability tiers).

    ``available`` is the concrete, local, discovery-derived ladder ordered weakest → strongest.
    The shared registry stores only the selection policy. Without ``available`` the binding uses
    semantic fallback labels and carries a warning; generated file-backed agents then omit concrete
    model frontmatter instead of pretending those labels are valid vendor model ids.
    """
    vendor_data = registry[vendor]
    semantic = not available
    rungs = list(available) if available else _semantic_rungs(vendor_data)
    if not rungs:
        rungs = _semantic_rungs(vendor_data)

    auditor = rungs[-1]  # pinned max, always — unlike the now-dynamic reasoner
    worker = rungs[0]
    worker_pos = rungs.index(worker)
    mid = rungs[min(worker_pos + 1, len(rungs) - 1)]
    escalation = tuple(rungs[worker_pos + 1 : len(rungs) - 1])

    policy = vendor_data.get("selection_policy", {})
    reasoner_policy = policy.get("reasoner", "highest")
    if semantic:
        fallback = vendor_data.get("semantic_fallback", {})
        reasoner = str(fallback.get("reasoner") or "strongest")
    elif reasoner_policy == "orchestrator" and orchestrator in rungs:
        reasoner = orchestrator
    else:
        # Unknown orchestrator, or a non-"orchestrator" policy value (e.g. "highest") —
        # fall back to the top rung.
        reasoner = rungs[-1]

    warning = None
    if semantic:
        warning = (
            "using semantic model labels because no concrete model list was provided; "
            "run model discovery or pass --available to bind vendor aliases locally"
        )
    else:
        floor = policy.get("orchestrator_floor", "highest")
        floor_rung = rungs[-1] if floor == "highest" else str(floor)
        if orchestrator not in rungs:
            warning = (
                f"orchestrator '{orchestrator}' is not in the discovered model list — "
                "cannot rank it against the floor; refresh discovery or check the alias"
            )
        elif floor_rung in rungs:
            # Healthy corridor: floor ≤ orchestrator < top (design §3, ADR 0006). When the
            # ladder tops out at the floor, floor == top and both arms stay silent — the
            # accepted degraded mode. A floor alias absent from the ladder disables the
            # check (nothing to rank against); the relative "highest" floor resolves to the
            # top rung, reproducing the pre-corridor below-top warning.
            orch_rank, floor_rank = rungs.index(orchestrator), rungs.index(floor_rung)
            if orch_rank < floor_rank:
                warning = (
                    f"orchestrator={orchestrator} is below the orchestration floor ({floor_rung}) — "
                    "decomposition/synthesis degrade everything downstream; consider /model up. "
                    "Advisory: the auditor's level verdict is the authoritative check"
                )
            elif orch_rank == len(rungs) - 1 and floor_rank < len(rungs) - 1:
                warning = (
                    f"orchestrator={orchestrator} runs on the auditor's reserved top rung — "
                    f"orchestration does not need it; consider /model down to {floor_rung}"
                )

    provider = opposite_vendor(registry, vendor)
    second_opinion = registry.get(provider, {}).get("second_opinion", {})
    return Binding(
        vendor=vendor,
        orchestrator=orchestrator,
        reasoner=reasoner,
        worker=worker,
        mid=mid,
        auditor=auditor,
        escalation=escalation,
        semantic_fallback=semantic,
        warning=warning,
        second_opinion_cli=second_opinion.get("harness"),
    )


def task_kind_floors(registry: dict, rungs: list[str]) -> dict[str, str]:
    """Per-task-kind rung floors, resolved to concrete aliases from ``rungs``.

    Only task kinds carrying a ``"floor"`` key are included. ``"highest"`` resolves to
    ``rungs[-1]``; a literal alias passes through only when present in ``rungs``. A kind
    whose floor cannot be resolved (empty ``rungs``, or an alias absent from it) is skipped.
    """
    floors: dict[str, str] = {}
    if not rungs:
        return floors
    for kind, spec in registry.get("task_kinds", {}).items():
        floor = spec.get("floor")
        if not floor:
            continue
        if floor == "highest":
            floors[kind] = rungs[-1]
        elif floor in rungs:
            floors[kind] = str(floor)
    return floors


def vendors_with_routing_policy(registry: dict) -> list[str]:
    """Vendors that can run a main/orchestrator session under the semantic routing policy."""
    return [
        name
        for name, spec in registry.items()
        if isinstance(spec, dict) and isinstance(spec.get("selection_policy"), dict)
    ]


def opposite_vendor(registry: dict, vendor: str) -> str:
    """Default second-opinion provider: another configured vendor, preferring the recorded order."""
    for candidate in vendors_with_routing_policy(registry):
        if candidate != vendor and second_opinion_spec(registry, candidate, required=False):
            return candidate
    return vendor


#: Keys C57 retired when the executable moved into ``common/runtime.py``. A project overlay written
#: before that change deep-merges *over* the shipped registry, so the new keys survive and the
#: stale ones ride along unread — the config looks usable and silently means something else.
RETIRED_SECOND_OPINION_KEYS = ("cli", "invoke")


def second_opinion_spec(registry: dict, provider: str, *, required: bool = True) -> dict:
    """The second-opinion policy for one provider, or ``{}`` when it is absent and optional.

    A spec still carrying the retired keys always raises, in both the required and optional
    calls: it is a stale *configuration*, not an absent capability, and degrading it to "no
    second opinion available" would hide the migration behind a silently weaker run.
    """
    spec = registry.get(provider, {}).get("second_opinion", {})
    if isinstance(spec, dict):
        retired = [key for key in RETIRED_SECOND_OPINION_KEYS if key in spec]
        if retired:
            raise KeyError(
                f"second-opinion provider '{provider}' still carries the retired key(s) "
                f"{', '.join(retired)}; the executable and its argv moved into common/runtime.py "
                f"(C57). Delete only those keys from the hand-owned project overlay and "
                f"leave the rest of the object alone: the overlay is deep-merged over the "
                f"shipped registry, so harness/operation/report_dir are inherited unless the "
                f"overlay deliberately overrides one. The initializer reads this file and will "
                f"not rewrite it; re-run it afterwards to refresh the generated config."
            )
        if spec.get("harness") and spec.get("operation") and spec.get("report_dir"):
            return spec
    if required:
        raise KeyError(f"second-opinion provider '{provider}' has no usable harness/operation/report_dir spec")
    return {}


def second_opinion_fallback_model(rungs: list[str], orchestrator: str, auditor: str) -> str | None:
    """The same-vendor fallback rung when no other vendor is reachable (design §9.7 #2).

    The diversity requirement is about *model* priors, not vendor branding: the strongest
    rung that differs from both the orchestrator (the author) and the auditor. ``None`` when
    no rung differs from the orchestrator at all (a single distinct rung) — the caller warns
    or skips; it must never fall back to the same model.
    """
    for rung in reversed(rungs):
        if rung not in (orchestrator, auditor):
            return rung
    return None


def second_opinion_command(spec: dict, prompt: str, model: str | None = None) -> list[str]:
    """Build the non-interactive CLI command; the prompt is passed as the final argv.

    The executable and the operation's argv come from the single owner in ``common/runtime.py``;
    the registry contributes only *policy* — which harness, which operation, and the optional
    ``model_flag`` format string (e.g. ``"--model {model}"``) inserted before the prompt so the
    same-vendor branch of the diversity ladder can pin a *different* model.
    """
    argv = harness_command(str(spec["harness"]), str(spec["operation"]))
    if model:
        model_flag = spec.get("model_flag")
        if model_flag:
            argv += shlex.split(str(model_flag).format(model=model))
    return [*argv, prompt]


def second_opinion_unavailability(registry: dict, config: dict, orchestrator_vendor: str) -> str:
    """Why no model-diverse reviewer exists, walked step by step over the configured ladder.

    Deliberately not a second verdict: ``resolve_second_opinion`` owns the answer. This states,
    per ladder step, the population that step had — and it states a *conclusion* ("nothing
    differs") only where it derives one from the same helper the ladder uses. A step that was
    never attempted says so instead of being explained away, because an overlay can shorten
    the ladder, and "no diverse reviewer" then means something entirely different.
    """
    policy = registry.get("second_opinion_policy", {}) if isinstance(registry, dict) else {}
    ladder = policy.get("diversity_ladder") or ["other-vendor", "same-vendor-other-model"]
    others = [
        vendor
        for vendor in vendors_with_routing_policy(registry)
        if vendor != orchestrator_vendor and second_opinion_spec(registry, vendor, required=False)
    ]
    configured = config.get("second_opinion_provider")
    rungs = config.get("available") or _semantic_rungs(registry.get(orchestrator_vendor, {}))
    orchestrator = str(config.get("orchestrator") or "?")
    auditor = str(config.get("binding", {}).get("auditor") or "?")
    against = f"the orchestrator '{orchestrator}' and the auditor '{auditor}'"

    if "other-vendor" not in ladder:
        other_vendor = "other-vendor: not attempted, it is absent from the configured ladder"
    elif not others:
        other_vendor = "other-vendor: no other vendor is configured with a usable second-opinion spec"
    elif isinstance(configured, str) and configured == orchestrator_vendor:
        other_vendor = (
            f"other-vendor: skipped because second_opinion_provider pins '{configured}', the "
            f"orchestrating vendor, though {', '.join(others)} is configured"
        )
    else:
        other_vendor = f"other-vendor: {', '.join(others)} configured with a usable spec"

    if "same-vendor-other-model" not in ladder:
        same_vendor = "same-vendor-other-model: not attempted, it is absent from the configured ladder"
    elif second_opinion_fallback_model(rungs, orchestrator, auditor) is None:
        same_vendor = (
            f"same-vendor-other-model: on '{orchestrator_vendor}' the rungs {rungs} hold none "
            f"that differs from both {against}"
        )
    else:
        same_vendor = f"same-vendor-other-model: on '{orchestrator_vendor}' the rungs {rungs} against {against}"
    return f"{other_vendor}; {same_vendor}"


@dataclass(frozen=True)
class SecondOpinionTarget:
    """A resolved second-opinion target: which provider, and which model to pin (if any)."""

    provider: str
    model: str | None  # None = the provider CLI's default model (other-vendor case)


def resolve_second_opinion(registry: dict, config: dict, orchestrator_vendor: str) -> SecondOpinionTarget | None:
    """Walk `second_opinion_policy.diversity_ladder` to a (provider, model) target.

    Diversity is about *model priors* (design §9.3 item 3): the reviewer must differ
    from the models it reviews. Ladder steps (registry data):
      - "other-vendor": another configured vendor with a usable spec — different priors
        by construction, so model=None (its CLI default is already a different model);
      - "same-vendor-other-model": the same vendor, pinned to the strongest rung that
        differs from BOTH orchestrator (author) and auditor, via
        `second_opinion_fallback_model` (design §9.7 #2);
      - `never: same-model` — if no rung differs, return None (skip); the caller must
        never fall back to the same model.

    An explicit `config["second_opinion_provider"]` is honored: a configured *other*
    vendor satisfies the other-vendor step; configured == orchestrator vendor routes to
    the same-vendor branch.
    """
    policy = registry.get("second_opinion_policy", {}) if isinstance(registry, dict) else {}
    ladder = policy.get("diversity_ladder") or ["other-vendor", "same-vendor-other-model"]
    orchestrator = str(config.get("orchestrator") or "")
    auditor = str(config.get("binding", {}).get("auditor") or "")
    configured = config.get("second_opinion_provider")
    for step in ladder:
        if step == "other-vendor":
            # An explicit same-vendor override is a deliberate "stay on my vendor, pin a
            # different model" choice — skip the other-vendor step so it falls through to
            # same-vendor-other-model rather than silently picking the opposite vendor.
            if isinstance(configured, str) and configured == orchestrator_vendor:
                continue
            provider = (
                configured
                if isinstance(configured, str) and configured and configured != orchestrator_vendor
                else opposite_vendor(registry, orchestrator_vendor)
            )
            if provider != orchestrator_vendor and second_opinion_spec(registry, provider, required=False):
                return SecondOpinionTarget(provider, None)
        elif step == "same-vendor-other-model":
            provider = orchestrator_vendor
            if not second_opinion_spec(registry, provider, required=False):
                continue
            model = config.get("second_opinion_fallback_model")
            if not model:
                rungs = config.get("available") or _semantic_rungs(registry.get(provider, {}))
                model = second_opinion_fallback_model(rungs, orchestrator, auditor)
            if model:
                return SecondOpinionTarget(provider, str(model))
    return None


# --------------------------------------------------------------------------------------
# Generated subagent definitions (the `k-` akmon namespace)
# --------------------------------------------------------------------------------------


# Each agent groups the task kinds whose briefs coincide; the tier picks its model from
# the binding. Bodies are project-neutral (this is SHARED); project specifics are appended
# via the overlay's "briefs" map.
@dataclass(frozen=True)
class AgentSpec:
    """One generated ``k_*`` subagent's definition: tier, description, tools, body, task kinds."""

    name: str
    tier: str  # "worker" | "mid" | "reasoner" | "auditor"
    description: str
    tools: str | None  # frontmatter `tools:`; None = all tools
    body: str
    kinds: tuple[str, ...] = field(default=())


AGENT_SPECS: tuple[AgentSpec, ...] = (
    AgentSpec(
        name="k_explorer",
        tier="worker",
        kinds=("explore-search", "summarize"),
        description=(
            "Worker tier — task kinds `explore-search` and `summarize`. Use for read-only "
            "fan-out: find where something lives in code/docs, sweep many files, condense "
            "files/logs/docs into a brief. Returns conclusions, not file dumps."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **explorer** delegate: read-only reconnaissance for the orchestrating session.

- Answer the question you were given; do not expand scope.
- Return **conclusions with `file:line` references**, not raw file contents. Keep the
  report short enough to be pasted into another agent's context.
- Verify against the actual code/docs you read — never answer from memory of similar
  projects.
- Never edit anything; you have no write tools by design. Bash is for **read-only
  inspection only** — `git log/diff/show/status`, `ls`, `jq` over local files; never run
  a command that mutates files, state, or history.
- **Escalation signal:** if the question is ambiguous, the evidence is contradictory, or
  the answer requires a judgment call beyond locating facts — say so explicitly in one
  short paragraph instead of guessing. The orchestrator escalates on that signal.""",
    ),
    AgentSpec(
        name="k_mechanic",
        tier="worker",
        kinds=("mech-edit", "test-scaffold", "doc-sync"),
        description=(
            "Worker tier — task kinds `mech-edit`, `test-scaffold`, `doc-sync`. Use for "
            "mechanical, behaviour-preserving work from an explicit spec: renames, sweeps, "
            "formatting, moving code without reshaping it, test skeletons/fixtures from a "
            "stated spec, propagating an already-decided fact across docs."
        ),
        tools=None,
        body="""You are the **mechanic** delegate: mechanical realization of an explicit spec.

- Execute the spec exactly; the decisions are already made — you make none. Match the
  surrounding code's naming, idiom, and comment density.
- Behaviour-preserving means behaviour-preserving: no drive-by refactors, no "while I'm
  here" improvements, no unrelated edits.
- Follow the project's guardrails (AGENTS.md): its import conventions, its command
  runner; artifacts (comments, docs) in English.
- Run the checks the spec names (the project's lint/test commands) and report their real
  output. Never `git add`/`commit`/`push` — the owner owns commits.
- **Escalation signal:** if the spec is ambiguous, incomplete, or executing it would
  require a decision (an interface reshape, a naming convention, a contract change) —
  stop and return a short report saying exactly what is undecided. Do not improvise.""",
    ),
    AgentSpec(
        name="k_validator",
        tier="worker",
        kinds=("validate-loop",),
        description=(
            "Worker tier — task kind `validate-loop`. Use to drive project gates to green: "
            "run tests/lint/verification tools, parse the output, apply minimal mechanical "
            "fixes, re-run until green — or stop with a diagnosis when the failure is not "
            "mechanical."
        ),
        tools=None,
        body="""You are the **validator** delegate: the run → parse → fix → re-run loop.

- Gates you run (as instructed by the task): the project's test and lint commands
  (AGENTS.md names them), and akmon's `bin/verify.py --strict` / `bin/sync.py --check`
  when named.
- **Fix scope is strictly mechanical:** missing/stale imports, autofixable lint,
  formatting, wrong paths/names after a rename, a test asserting a message that
  trivially changed. Apply the smallest fix that makes the gate pass, re-run, repeat.
- **Never touch** math, data shapes, contracts, or architecture — that is owner-verify
  territory: stop and report instead. Never weaken a test to make it pass; never delete
  or skip a failing test. Never `git add`/`commit`/`push`.
- Report at the end: gates run, final status per gate, fixes applied (file:line), and —
  for anything you did not fix — the failure evidence and your one-paragraph diagnosis.
- **Escalation signal:** two re-runs without progress, or any fix that would exceed the
  mechanical scope — stop and return the diagnosis; the orchestrator escalates.""",
    ),
    AgentSpec(
        name="k_implementer",
        tier="mid",
        kinds=("implement-under-spec",),
        description=(
            "Worker tier, mid rung — task kind `implement-under-spec`. Use to write code "
            "against a decided contract/design: the signatures, data shapes, and structure "
            "are already fixed; no open design decisions remain. Ships the change with its "
            "tests."
        ),
        tools=None,
        body="""You are the **implementer** delegate: realize a decided design in code.

- Implement exactly the stated contract (signatures, data shapes, placement). Reuse the
  project's abstractions (AGENTS.md names the load-bearing ones) — extend them, don't
  fork them.
- A behaviour change ships with a test; tests mirror the source layout. Run the project's
  test and lint commands (targeted first, then as instructed); report real output,
  including failures.
- Follow the guardrails and the language profile: type hints on public surfaces, every callable reads as
  `f(subject, *rest)` — subject first. Artifacts in English.
- Never `git add`/`commit`/`push` — the owner owns commits. Changes to math or data
  shape are owner-verified — flag them explicitly in your report.
- **Escalation signal:** if a load-bearing decision *emerges mid-build* (a new
  convention, an interface reshape, a contract change) — **stop**, per code-flow: report
  the gap instead of deciding it. Same if the given contract contradicts the code you
  find.""",
    ),
    AgentSpec(
        name="k_reasoner",
        tier="reasoner",
        kinds=("debug-deep", "design-fork", "quant-derivation", "plan-draft"),
        description=(
            "Reasoner tier — task kinds `debug-deep`, `design-fork`, `quant-derivation`, "
            "`plan-draft`. Use for load-bearing thinking: multi-cause/cross-boundary "
            "failure analysis, drafting options for a contested design fork, deriving "
            "pricing/quant math, drafting a decomposition/zone plan for the orchestrator. "
            "Returns a structured report; it drafts, it never decides or edits."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **reasoner** delegate: load-bearing analysis and drafting for the
orchestrating session. You produce a report — you do not edit files, and your output is
a draft for the owner's verification, never a decision.

- **debug-deep:** read the code, reproduce with read-only commands (the project's test
  runner), and return: the failure mechanism, the evidence chain (`file:line`), candidate
  causes ranked, and the minimal fix criteria — not the fix itself unless asked.
- **design-fork:** frame the design space — realistic options including the status quo,
  evaluation criteria, trade-offs, risks, revisit-if conditions. Recommend one; never
  present a single option as inevitable.
- **quant-derivation:** derive step by step, state assumptions and domain boundaries;
  respect the project's numeric conventions (quant profile). Every formula is explicitly
  flagged for owner verification — plausibility is not agreement.
- **plan-draft:** draft the work decomposition — the zone plan (named zones/modules the
  fan-out splits by), risks, ordering, and what would prove the plan wrong. A draft for
  the orchestrator to adopt or reject — never route or spawn work yourself.
- Verify names, signatures, and paths in the actual code before reasoning from them.
- **Escalation signal:** if the question cannot be answered without information only the
  owner has (intent, priorities, external constraints), return the precise question to
  ask rather than an assumption dressed as analysis.""",
    ),
    AgentSpec(
        name="k_auditor",
        tier="auditor",
        kinds=("audit",),
        description=(
            "Auditor tier — task kind `audit`. Clean-context audit of a "
            "whole gate's collected material (a gate-pack): contradictions between "
            "independently-correct findings, uncovered seams between zones, re-ranking "
            "deltas, a level verdict. Pinned to the maximal available model; drafts and "
            "audits, never edits."
        ),
        tools="Read, Grep, Glob, Bash",
        body="""You are the **auditor** delegate: a clean-context audit of a gate's whole
collected material — the first check on the orchestrator's own synthesis.

- You receive a **gate-pack** (artifacts + the Frame-stage yardstick + a coverage map)
  and nothing else — no session history. The clean context is the mechanism: judge
  against the stated yardstick, not one inferred from the findings in front of you.
- Output exactly these sections:
  - **Contradictions** — between independently-correct findings/options.
  - **Uncovered seams** — derived from the coverage map: zones no worker checked,
    boundaries between zones.
  - **Re-ranking / recommendation deltas.**
  - **Level verdict** — does the material suggest the task exceeded the session-model
    hypothesis; if so, name the specific piece to redo on a higher rung, or recommend
    `/model` up.
  - **Could not verify** — an explicit list.
- Bash is for **read-only inspection only** (e.g. grep-derived dependency edges) — never
  a command that mutates files, state, or history.
- Your report is advisory — the orchestrator and owner decide; you never edit.
- **Escalation signal:** if the pack lacks what the audit needs (no coverage map, no
  yardstick), return the precise gap instead of a diluted verdict.""",
    ),
)


def _agent_model(spec: AgentSpec, binding: Binding) -> str | None:
    if binding.semantic_fallback:
        return None
    return {
        "worker": binding.worker,
        "mid": binding.mid,
        "reasoner": binding.reasoner,
        "auditor": binding.auditor,
    }[spec.tier]


def agent_file_content(spec: AgentSpec, binding: Binding, brief_extra: str = "") -> str:
    """Render one generated ``.claude/agents/<name>.md`` file: frontmatter, banner, body, brief."""
    lines = ["---", f"name: {spec.name}", "description: >-"]
    lines.extend(f"  {chunk}" for chunk in _wrap(spec.description, 88))
    if spec.tools:
        lines.append(f"tools: {spec.tools}")
    model = _agent_model(spec, binding)
    if model:
        lines.append(f"model: {model}")
    lines.append("---")
    lines.append("")
    lines.append(f"<!-- {GENERATED_BANNER} -->")
    lines.append("")
    lines.append(spec.body)
    if brief_extra.strip():
        lines.append("")
        lines.append("<!-- project overlay brief -->")
        lines.append("")
        lines.append(brief_extra.strip())
    return "\n".join(lines) + "\n"


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    chunks: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            chunks.append(current)
            current = word
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks


class BriefError(ValueError):
    """A project overlay's ``briefs`` map cannot be applied to the current agent specs.

    Raised instead of defaulting to an empty brief: an overlay brief is hand-authored
    project instruction, and a key that matches no agent means those instructions would
    silently vanish from the generated definition — no diff to look at, no warning. That is
    the tolerance-degrades-to-silence shape C48 argues against, and ADR 0011's ``k-*`` →
    ``k_*`` rename made it live (C50).
    """


def agent_key(name: str) -> str:
    """Normal form of an agent name for overlay lookups — folds case, ``-``/``_`` and surrounding whitespace.

    Overlay brief keys are a public contract written by hand in a consumer's repository, so
    a change of *notation* (ADR 0011) must not orphan them. The tolerance line, owner-verified
    at D2-16(b): invisible and notational differences are forgiven — surrounding whitespace does
    not survive a diff, so failing on it costs more to diagnose than the tolerance costs to hold
    — while any difference in significant characters, an internal space included, still fails
    (see ``resolve_briefs``).
    """
    return name.strip().lower().replace("-", "_")


def resolve_briefs(registry: dict) -> dict[str, str]:
    """Overlay briefs re-keyed by the **current** spec names; raises ``BriefError`` otherwise."""
    briefs = registry.get("briefs", {})
    if not isinstance(briefs, dict):
        raise BriefError(f"overlay 'briefs' must be an object, got {type(briefs).__name__}")
    by_key = {agent_key(spec.name): spec.name for spec in AGENT_SPECS}
    resolved: dict[str, str] = {}
    source: dict[str, str] = {}
    for key, text in sorted(briefs.items()):
        if not isinstance(text, str):
            raise BriefError(f"overlay brief '{key}' must be a string, got {type(text).__name__}")
        name = by_key.get(agent_key(str(key)))
        if name is None:
            known = ", ".join(sorted(by_key.values()))
            raise BriefError(f"overlay brief key '{key}' matches no agent (known: {known})")
        if name in resolved:
            raise BriefError(f"overlay brief keys '{source[name]}' and '{key}' both resolve to '{name}'")
        source[name] = str(key)
        resolved[name] = text
    return resolved


def brief_warning(registry: dict, aitna: str | None = None) -> str | None:
    """Owner-addressed line naming an unusable overlay ``briefs`` map, or None when it is fine."""
    try:
        resolve_briefs(registry)
    except BriefError as exc:
        root = aitna or aitna_root_name()
        return f"⚠ {exc} — fix {root}/{OVERLAY_NAME}; k_* definitions are not regenerated until it resolves"
    return None


def suppressed_rebind_warning(
    warning: str | None,
    detected_model: str | None,
    session_id: str | None,
    *,
    marker_dir: Path | None = None,
) -> list[str]:
    """Emit one warning per session/model/error episode; reset when the condition clears.

    A refused rebind leaves the recorded orchestrator unchanged, so comparing the next
    transcript against that config reports the same switch on every prompt. The marker is
    deliberately temporary rather than project state: it remembers only which warning the
    current session already saw. A changed model or error produces a new digest and re-arms
    the notice; a cleared condition removes the marker so a later recurrence speaks again.

    Delivery here is **best-effort, and this is the one place akmon accepts fail-quiet**
    (D2-22). A stale marker hides the switch-time notice only when three things coincide: a
    session id that survived a crash or was reused, the same detected model, and the same
    warning text. It is tolerable only because the same condition is reported loudly
    elsewhere — SessionStart's ``BriefError`` and a direct ``init.py`` run — so this must not
    be read as licence to go quiet in general. The acceptance ends with C36(a): once the
    marker moves onto the atomic hook helper and gains an age-out, exactly-once per episode
    becomes the contract.
    """
    # Without a reliable session identity, never let one anonymous invocation silence
    # another session. Repeating the warning is safer than a process-global ``nosession``
    # marker that hides an unresolved lossy-rebind condition from an unrelated owner.
    if not session_id:
        return [warning] if warning is not None and detected_model is not None else []

    session = str(session_id)
    marker_name = hashlib.sha256(session.encode()).hexdigest()[:20]
    marker = (marker_dir or Path(tempfile.gettempdir())) / f"akmon-suppressed-rebind-{marker_name}"
    if warning is None or detected_model is None:
        with contextlib.suppress(OSError):
            marker.unlink(missing_ok=True)
        return []

    condition = hashlib.sha256(f"{detected_model}\0{warning}".encode()).hexdigest()
    try:
        if marker.read_text(encoding="utf-8") == condition:
            return []
    except OSError:
        pass
    with contextlib.suppress(OSError):
        marker.write_text(condition, encoding="utf-8")
    return [warning]


def generated_agent_files(registry: dict, binding: Binding) -> dict[str, str]:
    """Map of ``.claude/agents/<name>.md`` relative paths → generated content."""
    briefs = resolve_briefs(registry)
    return {
        f"{AGENTS_DIR_REL}/{spec.name}.md": agent_file_content(spec, binding, briefs.get(spec.name, ""))
        for spec in AGENT_SPECS
    }


_AGENT_BY_NAME: dict[str, AgentSpec] = {spec.name: spec for spec in AGENT_SPECS}


def subagent_kinds(name: str) -> tuple[str, ...]:
    """Task kinds a generated subagent covers; empty for a host built-in / unknown name."""
    spec = _AGENT_BY_NAME.get(name)
    return spec.kinds if spec else ()


def bound_model_for(config: dict, subagent_type: str) -> str | None:
    """Model a generated ``k_*`` agent is pinned to — its tier's binding alias, or None.

    The generated agent frontmatter carries ``model: <alias>`` (see ``_agent_model``), but an
    ``Agent`` call rarely echoes it — so the delegation record shows ``-`` and the console
    line omits the model. Deriving it from the recorded binding restores it. None for an
    unknown agent (a host built-in) or for a semantic-fallback binding, whose tier values are
    labels (``worker``/``strongest``), not vendor aliases.

    The config does not persist ``Binding.semantic_fallback``, so the mode is re-derived the
    same way ``compute_binding`` decides it: **no recorded ``available`` ladder is exactly
    semantic fallback**. That is the mirror of ``_agent_model`` emitting no ``model:`` line —
    an agent file without a pin is inherited by the host from the session, so there is no pin
    to report and the record honestly says ``-``. Reporting the label instead would assert a
    pin precisely where the design refuses to make one.
    """
    spec = _AGENT_BY_NAME.get(subagent_type)
    if spec is None or not isinstance(config, dict):
        return None
    binding = config.get("binding")
    if not isinstance(binding, dict):
        return None
    model = binding.get(spec.tier)
    if not isinstance(model, str) or not model:
        return None
    available = config.get("available")
    if (
        not isinstance(available, list)
        or not available
        or not all(isinstance(alias, str) for alias in available)
        or model not in available
    ):
        return None
    return model


_ROLE_DECL_RE = re.compile(r"\A\s*🧭\s*agent:\s*([A-Za-z][\w-]*)")


def _assistant_text(entry: dict) -> str:
    message = entry.get("message")
    if not isinstance(message, dict):
        return ""
    content = message.get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(
            block.get("text", "") for block in content if isinstance(block, dict) and block.get("type") == "text"
        )
    return ""


def active_role(transcript_path: str | Path | None) -> str | None:
    """The role from the last qualifying ``🧭 agent: <name>`` transcript declaration.

    The chat declaration is invisible to a hook as chat, but the transcript records it in the
    assistant turns a hook can already scan (as C22/C23 do). Only main-chain assistant turns
    are read, so the SessionStart reminder / a subagent echo never masquerades as the
    declaration. A declaration qualifies only as the first non-whitespace text of its turn,
    so later inline and Markdown-prefixed examples cannot change state. A first-position marker
    is a declaration by definition. Returns the case-normalized role name, else None.
    """
    if not transcript_path:
        return None
    path = Path(transcript_path)
    if not path.is_file():
        return None
    role: str | None = None
    try:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                # Cheap ascii pre-filter: the emoji may be \u-escaped in the JSONL, but
                # "agent:" is always literal. json.loads then decodes the real marker.
                if "agent:" not in line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(entry, dict) or entry.get("type") != "assistant" or entry.get("isSidechain"):
                    continue
                match = _ROLE_DECL_RE.match(_assistant_text(entry))
                if match:
                    role = match.group(1).casefold()
    except OSError:
        return None
    return role


def role_matrix_warning(registry: dict, subagent_type: str, role: str | None) -> str | None:
    """Conservative advisory (§10.2): the agent has no effectively allowed task kind.

    The call carries the agent, not an authoritative invocation kind, so warn only when *none*
    of the agent's kinds intersect the role's effective allowed set. Silence proves one allowed
    overlap, not conformance of an intended kind carried by a multi-kind agent. None when the
    role is unknown/undeclared or the agent is a host built-in (no kinds).

    **Cross-cutting verification kinds** (``cross_cutting_kinds`` — ``independent-review`` and
    ``audit``) are *not* role-gated (A7 (b), §10.2): any role may route them and *when* they
    apply is the structural trigger (§9.5), not the producing role. They join every role's
    allowed set, so an agent whose only kinds are cross-cutting (e.g. ``k_auditor``) never
    warns under any role.
    """
    if not role:
        return None
    role_rows = registry.get("role_task_kinds", {})
    if not isinstance(role_rows, dict) or role not in role_rows:
        return None
    allowed = role_rows[role]
    if not isinstance(allowed, list):
        return None
    effective_allowed = tuple(dict.fromkeys((*allowed, *registry.get("cross_cutting_kinds", []))))
    kinds = subagent_kinds(subagent_type)
    if not kinds or set(kinds) & set(effective_allowed):
        return None
    allowed_text = ", ".join(effective_allowed) or "no task kinds"
    return (
        f"role/task-kind: {subagent_type} ({', '.join(kinds)}) is outside the active role "
        f"'{role}' — it routes {allowed_text}. Re-route or switch role."
    )


# --------------------------------------------------------------------------------------
# Local config + status line (the SessionStart hook contract)
# --------------------------------------------------------------------------------------


def resolve_alias(model_id: str | None, available: list[str] | None) -> str | None:
    """Map a concrete vendor model id (e.g. ``claude-opus-4-8``) to a known local alias.

    The alias is matched as a case-insensitive substring of the id, preferring the longest
    match so overlapping aliases disambiguate (``opus`` over a bare ``o``). ``None`` when no
    alias in ``available`` matches — the caller keeps the recorded binding rather than guess.
    """
    if not model_id or not available:
        return None
    lowered = model_id.lower()
    matches = [alias for alias in available if alias and alias.lower() in lowered]
    return max(matches, key=len) if matches else None


def _last_main_turn(transcript_path: str | Path | None) -> tuple[str | None, dict | None]:
    """(model id, usage) of the last *main-chain* assistant turn in the session transcript.

    The transcript (a JSONL the harness records; its path arrives in the hook payload)
    carries ``message.model`` and ``message.usage`` per assistant turn. Sidechain
    (subagent) turns and synthetic entries are skipped, so a delegate's model or usage
    never masquerades as the orchestrator's. One pass yields both facts — orchestrator
    detection and context-pressure detection share it. ``(None, None)`` when the
    transcript is missing/empty/unreadable or names no model yet.
    """
    if not transcript_path:
        return None, None
    path = Path(transcript_path)
    if not path.is_file():
        return None, None
    model_id: str | None = None
    usage: dict | None = None
    try:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if '"model"' not in line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(entry, dict) or entry.get("type") != "assistant" or entry.get("isSidechain"):
                    continue
                message = entry.get("message")
                model = message.get("model") if isinstance(message, dict) else None
                if isinstance(model, str) and model and not model.startswith("<"):
                    model_id = model
                    entry_usage = message.get("usage")
                    usage = entry_usage if isinstance(entry_usage, dict) else None
    except OSError:
        return None, None
    return model_id, usage


def detect_orchestrator(transcript_path: str | Path | None, available: list[str] | None) -> str | None:
    """Alias of the model the *main chain* last ran on, read from the session transcript.

    ``None`` when the transcript names no model yet or the model maps to no known alias
    (a fresh session before the first turn, or an unrecognized id): the caller then keeps
    the recorded orchestrator instead of guessing.
    """
    model_id, _ = _last_main_turn(transcript_path)
    return resolve_alias(model_id, available)


# --------------------------------------------------------------------------------------
# Context-pressure detection (design §12, ADR 0006) — the tokens axis of runtime weakness
# --------------------------------------------------------------------------------------


def context_fill(usage: dict | None) -> int | None:
    """Context fill at a turn: the three input components partition the prompt.

    ``output_tokens`` is not context carried forward, so it is excluded. ``None`` unless all
    three input components are non-negative integers (a bool is not a count): one valid
    component never stands in for the prompt, so the caller stays silent rather than warn
    from a partial or malformed record.
    """
    if not isinstance(usage, dict):
        return None
    components = [usage.get(key) for key in ("input_tokens", "cache_read_input_tokens", "cache_creation_input_tokens")]
    if not all(isinstance(value, int) and not isinstance(value, bool) and value >= 0 for value in components):
        return None
    return sum(components)


#: Overrides the recommended maximum for every model when it holds a positive integer — per user
#: (the shell, or ``env`` in ``~/.claude/settings.json``) or per project (``env`` in
#: ``.claude/settings.json``). Any other value is ignored and the registry decides.
RECOMMENDED_MAX_ENV = "AKMON_CONTEXT_RECOMMENDED_MAX"


def recommended_max_context(registry: dict, model_id: str | None) -> int:
    """The recommended context budget, in tokens — what pressure percentages are a share of.

    The recommended active-context budget for a session intended to carry one task, not the
    model's hard limit (design §12.2): a session should carry the task it is solving, not its
    history — fewer tokens spent, less drift from the task, less forgetting — and quality
    degrades with length whatever the limit. This code knows neither which task a session
    carries nor what that task needs; it sees only the prompt fill. Resolution:
    ``AKMON_CONTEXT_RECOMMENDED_MAX`` when it holds a positive integer, else the longest
    alias-substring key of ``recommended_max_by_alias`` found in the model id (e.g. a model whose
    hard limit sits below the default), else ``recommended_max``. The shipped 200000 is a
    configurable owner policy checked against measurement — above where sessions get compacted
    in practice, below the 258,400-token window Codex reports for OpenAI models — C80
    (meta/reviews/c80-context-fill-20260912.md).
    """
    try:
        override = int(os.environ.get(RECOMMENDED_MAX_ENV, ""))
    except ValueError:
        override = 0
    if override > 0:
        return override
    policy = registry.get("context_pressure", {})
    default = int(policy.get("recommended_max") or 200000)
    by_alias = policy.get("recommended_max_by_alias", {})
    if model_id and isinstance(by_alias, dict):
        lowered = model_id.lower()
        matches = [key for key in by_alias if key and key.lower() in lowered]
        if matches:
            return int(by_alias[max(matches, key=len)])
    return default


def _context_fill_metrics(registry: dict, transcript_path: str | Path | None) -> tuple[int, int, float] | None:
    """``(fill, recommended_max, ratio)`` for the last main-chain turn; ``None`` if unavailable.

    Shared by ``context_pressure_notice`` (the two-level reminder) and ``context_fill_ratio``
    (the C29 axis-2 coefficient) so both read the same fill/recommended-max definition.
    """
    model_id, usage = _last_main_turn(transcript_path)
    fill = context_fill(usage)
    if fill is None:
        return None
    recommended = recommended_max_context(registry, model_id)
    if recommended <= 0:
        return None
    return fill, recommended, fill / recommended


def context_fill_ratio(registry: dict, transcript_path: str | Path | None) -> float | None:
    """Fill as a share of the recommended maximum for the last main-chain turn (can pass 1.0); ``None`` if unavailable.

    Reused by the C29 output-weight nudge to weight cumulative tool-output bytes by how far
    into the recommended maximum the session already is — the same signal
    ``context_pressure_notice`` bands.
    """
    metrics = _context_fill_metrics(registry, transcript_path)
    return metrics[2] if metrics else None


def context_pressure_notice(
    registry: dict,
    transcript_path: str | Path | None,
    session_id: str | None,
    *,
    marker_dir: Path | None = None,
) -> list[str]:
    """One reminder line when the context fill reached a *new* pressure level; ``[]`` otherwise.

    Two levels of the recommended budget (design §12.2): **info** at ``info_ratio`` and **warn**
    at the budget itself, 1.0 — fixed, since reaching the budget is what the budget means.
    Throttled (the delegation-nudge marker idiom): a per-session temp-dir marker records the last
    announced level, so only a rise speaks — info once, warn once more, also when the fill jumps
    straight past 100%; a steady fill and any fill past the budget stay silent. A fill below the
    lowest level ends the pressure episode and clears the marker — the hook sees only the low
    fill, not its cause (a compact, a fresh session, anything else). The share is of the
    recommended budget, not the model's limit, so it can pass 100% on a model with a larger
    window; going on is the developer's call. Missing/malformed usage → silent; never raises
    past I/O.
    """
    policy = registry.get("context_pressure", {})
    info_ratio = policy.get("info_ratio")
    # Only a share strictly between 0 and 1 is a level below the budget; anything else (absent,
    # a bool, 0, 1 or more, a string) leaves the budget's own warning alone.
    if isinstance(info_ratio, bool) or not isinstance(info_ratio, (int, float)) or not 0 < info_ratio < 1:
        info_ratio = None
    metrics = _context_fill_metrics(registry, transcript_path)
    if metrics is None:
        return []
    _, recommended, ratio = metrics
    level: int | None = None  # 0 = info, 1 = warn — the value the marker records
    if ratio >= 1.0:
        level = 1
    elif info_ratio is not None and ratio >= info_ratio:
        level = 0

    marker = (marker_dir or Path(tempfile.gettempdir())) / f"akmon-context-pressure-{session_id or 'nosession'}"
    try:
        last_level: int | None = int(marker.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        last_level = None

    if level is None:
        # Below every level — the pressure episode is over and the throttle resets. The cause is
        # not visible here: a compact, a fresh session and anything else that lowered the fill
        # look alike.
        with contextlib.suppress(OSError):
            marker.unlink(missing_ok=True)
        return []
    if last_level is not None and level <= last_level:
        return []
    with contextlib.suppress(OSError):
        marker.write_text(str(level), encoding="utf-8")

    shown = f"{recommended // 1000}k" if recommended % 1000 == 0 else str(recommended)
    share = f"~{ratio:.0%} of the recommended {shown} budget"
    # A reminder to the owner and nothing more: the share and the command to type. `/compact` and
    # `/new` exist under those names in Claude Code and in Codex alike. The marks are the hook's
    # own: ⚠ for a warning, as the corridor's, ℹ for information.
    if level == 1:
        return [f"⚠ context pressure: {share} — /compact; new task: /new"]
    return [f"ℹ context pressure: {share} — /compact"]


def binding_artifacts(
    registry: dict, binding: Binding, *, second_opinion: bool, available: list[str] | None
) -> dict[str, str]:
    """Every generated routing artifact as ``project-root-relative path → content``.

    The generated ``k_*`` subagent definitions plus the local config — the single set the
    init tool and the SessionStart/UserPromptSubmit hook both write, so a rebind from
    either path produces byte-identical files.
    """
    files = dict(generated_agent_files(registry, binding))
    config = local_config(binding, registry, second_opinion=second_opinion, available=available)
    files[LOCAL_CONFIG_REL] = json.dumps(config, indent=2) + "\n"
    return files


def obsolete_agent_files(root: Path, planned_paths: Iterable[Path]) -> list[Path]:
    """Generated subagent definitions on disk that the current ``AGENT_SPECS`` no longer plan.

    Only files carrying ``GENERATED_BANNER`` are candidates, so a hand-written agent living in
    the same directory is never a deletion target. Without this, renaming an agent leaves its
    old definition behind as a live duplicate — the harness keeps offering both, the stale one
    still pinned to a model, and nothing warns (``bin/sync.py`` prunes only skills, ADR 0011).
    """
    agents_dir = root / AGENTS_DIR_REL
    if not agents_dir.is_dir():
        return []
    planned = set(planned_paths)
    obsolete: list[Path] = []
    for path in sorted(agents_dir.glob("*.md")):
        if path in planned:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if GENERATED_BANNER in text:
            obsolete.append(path)
    return obsolete


def remove_obsolete_agents(root: Path, planned_paths: Iterable[Path], *, write: bool = True) -> list[Path]:
    """Delete the generated agent definitions no longer planned; return their paths."""
    removed = obsolete_agent_files(root, planned_paths)
    if write:
        for path in removed:
            path.unlink(missing_ok=True)
    return removed


def write_artifacts(root: Path, files: dict[str, str], *, write: bool = True) -> list[Path]:
    """Write each artifact whose content changed; return the changed paths (idempotent)."""
    changed: list[Path] = []
    for rel, content in files.items():
        path = root / rel
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        changed.append(path)
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return changed


def rebind_to(
    root: Path, registry: dict, config: dict, orchestrator: str, *, write: bool = True
) -> tuple[Binding, list[Path]]:
    """Recompute the binding for ``orchestrator`` and (re)write the artifacts under ``root``.

    Reuses the recorded ``available`` list and opt-ins from ``config`` — only the
    orchestrator moves. Idempotent: unchanged files are left untouched. This is how the
    hook makes subagent models follow the session's actual orchestrating model.
    """
    available = config.get("available")
    second_opinion = bool(config.get("second_opinion"))
    vendor = str(config.get("vendor") or "anthropic")
    binding = compute_binding(registry, orchestrator, available, vendor)
    files = binding_artifacts(registry, binding, second_opinion=second_opinion, available=available)
    changed = write_artifacts(root, files, write=write)
    remove_obsolete_agents(root, (root / rel for rel in files), write=write)
    return binding, changed


def local_config(binding: Binding, registry: dict, *, second_opinion: bool, available: list[str] | None) -> dict:
    """The per-user resolved config written to ``LOCAL_CONFIG_REL`` (binding, opt-ins, staleness hash)."""
    config = {
        "vendor": binding.vendor,
        "orchestrator": binding.orchestrator,
        "binding": {
            "reasoner": binding.reasoner,
            "worker": binding.worker,
            "mid": binding.mid,
            "auditor": binding.auditor,
            "escalation": list(binding.escalation),
        },
        "second_opinion": second_opinion,
        "second_opinion_provider": opposite_vendor(registry, binding.vendor),
        "available": available,
        "registry_hash": registry_hash(registry),
        "task_kind_floors": task_kind_floors(registry, available or []),
    }
    provider = config["second_opinion_provider"]
    if provider == binding.vendor:
        rungs = list(available) if available else _semantic_rungs(registry.get(binding.vendor, {}))
        config["second_opinion_fallback_model"] = second_opinion_fallback_model(
            rungs, binding.orchestrator, binding.auditor
        )
    return config


def staleness(config: dict, registry: dict, settings_model: str | None) -> str | None:
    """Why the local config is stale — or None when it is fresh."""
    if not config:
        return "no local config — model routing is not initialized"
    if config.get("registry_hash") != registry_hash(registry):
        return "registry (or project overlay) changed since init"
    if settings_model and settings_model != config.get("orchestrator"):
        return f"settings default model '{settings_model}' differs from configured orchestrator"
    return None


def _second_opinion_status(registry: dict, config: dict, orchestrator_vendor: str) -> tuple[str, str | None]:
    """What the second-opinion gate will actually do, as one status field plus any warning.

    Resolved through the same ladder the runner walks (``resolve_second_opinion``) rather
    than through the pre-ladder ``second_opinion_provider``: the latter names the
    *configured* provider, so an installation whose ladder is exhausted still read
    ``second-opinion=<harness>(on)`` while every gate silently skipped. A display that can
    disagree with the policy is a second owner of one fact — the drift class C46 exists to
    remove — so this one asks the policy.
    """
    enabled = bool(config.get("second_opinion"))
    state = "on" if enabled else "off"
    # A retired-key overlay (C57/D2-30) raises out of here, deliberately and not only here:
    # ``compute_binding`` reaches the same spec through ``opposite_vendor``, so a stale
    # overlay costs the whole status block, not this field. Catching it locally would look
    # like resilience while changing nothing, so the raise is left to travel.
    target = resolve_second_opinion(registry, config, orchestrator_vendor)
    if target is None:
        warning = (
            "second-opinion is on but the diversity ladder is exhausted: no reachable "
            "provider differs from the reviewed model, so every gate will skip it — "
            "second_opinion.py states the reason at the gate and names the one thing that "
            "can still be run by hand, with its limits"
        )
        return f"second-opinion=unavailable({state})", warning if enabled else None
    harness = str(second_opinion_spec(registry, target.provider, required=False).get("harness") or "-")
    pin = f", model={target.model}" if target.model else ""
    return f"second-opinion={harness}({state}{pin})", None


def status_lines(config: dict, registry: dict, runtime_root: str) -> list[str]:
    """The steady-state status injection: one binding line + self-check, plus any warning.

    ``runtime_root`` is the project-root-relative directory the routing tools actually live in
    — ``<AITNA_ROOT>/akmon`` when the standard is mounted, ``<AITNA_ROOT>/.akmon`` in mount mode
    ``package``, where there is no mount at all (ADR 0009 §4). It is passed in rather than
    derived here because only the caller knows the project root; naming the mount
    unconditionally used to hand a package-mode session a path that does not exist.
    """
    binding = config.get("binding", {})
    orchestrator_vendor = str(config.get("vendor") or "anthropic")
    second_display, second_warning = _second_opinion_status(registry, config, orchestrator_vendor)
    orchestrator = config.get("orchestrator", "?")
    lines = [
        "[akmon] model routing: "
        f"vendor={orchestrator_vendor} · orchestrator={orchestrator} · reasoner={binding.get('reasoner', '?')} · "
        f"auditor={binding.get('auditor', '?')} · "
        f"worker={binding.get('worker', '?')} · mid={binding.get('mid', '?')} · "
        f"{second_display}",
        "Delegation is the default — route by task kind (MODEL.md § Capability tiers): "
        "k_explorer/k_mechanic/k_validator (worker) · k_implementer (mid) · k_reasoner · "
        "k_auditor (audit at gates); escalate one rung only on failure signals.",
        f"Self-check: if your actual model is not '{orchestrator}', re-run "
        f"`python3 {runtime_root}/tools/model_routing/init.py --orchestrator <alias>`.",
    ]
    warning = compute_binding(registry, orchestrator, config.get("available"), orchestrator_vendor).warning
    if warning:
        lines.append(f"⚠ {warning}")
    if second_warning:
        lines.append(f"⚠ {second_warning}")
    return lines


def rebind_notice(config: dict, registry: dict) -> list[str]:
    """The concise mid-session note after the orchestrator model changed (UserPromptSubmit).

    One line naming the new orchestrator and the recomputed subagent binding, plus the
    weak-orchestrator warning when it applies — that warning is exactly what the owner
    wants surfaced on a switch *down* to a thin model.
    """
    binding = config.get("binding", {})
    orchestrator = config.get("orchestrator", "?")
    vendor = str(config.get("vendor") or "anthropic")
    lines = [
        f"[akmon] orchestrator model changed → {orchestrator}; subagent binding updated: "
        f"reasoner={binding.get('reasoner', '?')} · auditor={binding.get('auditor', '?')} · "
        f"worker={binding.get('worker', '?')} · mid={binding.get('mid', '?')}. "
        "Regenerated k_* agents follow the new model.",
    ]
    warning = compute_binding(registry, orchestrator, config.get("available"), vendor).warning
    if warning:
        lines.append(f"⚠ {warning}")
    return lines


def init_instruction(reason: str, runtime_root: str) -> list[str]:
    """The one-time setup instruction.

    ``runtime_root``: see ``status_lines`` — the recovery path must name the tree this
    project actually has, mounted or materialized.
    """
    return [
        f"[akmon] Model routing needs initialization — {reason}.",
        "State the model you are running on and the models available in this harness, then run: "
        f"`python3 {runtime_root}/tools/model_routing/init.py --orchestrator <your-alias> "
        "[--available <alias,...>] [--second-opinion on|off]`.",
        "Then ask the owner to (a) confirm the proposed tier→model binding and "
        "(b) enable or decline second-opinion review, and re-run the tool with their answers.",
    ]


# --------------------------------------------------------------------------------------
# Delegation log (the PreToolUse hook contract)
# --------------------------------------------------------------------------------------

_SUBAGENT_TOOLS = frozenset({"Task", "Agent"})


ZONE_MARKER_PREFIX = "[zone:"

#: Column counts for ``parse_delegation_entries``: the current schema (timestamp, session_id,
#: subagent, model, zone, description) and the legacy one (timestamp, subagent, model,
#: description — no session/zone).
_CURRENT_SCHEMA_COLUMNS = 6
_LEGACY_SCHEMA_COLUMNS = 4


def parse_zone(description: str) -> tuple[str | None, str]:
    """Split a leading ``[zone:LABEL]`` marker off a delegation description.

    The zone label rides in the description — the only free-form field a subagent call
    carries (§9.4/§10.3). A marker only counts at the very start:
    ``[zone:auth] check tokens`` -> ``("auth", "check tokens")``. No marker ->
    ``(None, <description stripped>)``.
    """
    text = description.strip()
    if text.startswith(ZONE_MARKER_PREFIX):
        end = text.find("]")
        if end != -1:
            label = text[len(ZONE_MARKER_PREFIX) : end].strip()
            rest = text[end + 1 :].strip()
            return (label or None, rest)
    return (None, text)


def delegation_log_line(
    tool_name: str,
    tool_input: dict,
    timestamp: str,
    session_id: str | None = None,
    bound_model: str | None = None,
) -> str | None:
    """One TSV line per subagent delegation; None for any other tool.

    Columns: ``timestamp · session_id · subagent · model · zone · description``. The zone
    is parsed off a leading ``[zone:LABEL]`` marker in the description (removed from the
    stored description); ``-`` marks an absent session / model / zone. The model is the
    call's explicit override if given, else ``bound_model`` (the agent's recorded tier pin,
    derived by the caller so the record + console line name the declared model selection).
    ``session_id`` scopes a fan-out round for the coverage-map assembler (C17).
    """
    if tool_name not in _SUBAGENT_TOOLS:
        return None
    subagent = str(tool_input.get("subagent_type") or "-")
    model = str(tool_input.get("model") or bound_model or "-")
    raw_description = " ".join(str(tool_input.get("description") or "").split())
    zone, description = parse_zone(raw_description)
    return f"{timestamp}\t{session_id or '-'}\t{subagent}\t{model}\t{zone or '-'}\t{description}"


@dataclass(frozen=True)
class DelegationEntry:
    """One parsed delegation-log row (schema: see ``delegation_log_line``)."""

    timestamp: str
    session_id: str | None
    subagent: str
    model: str | None
    zone: str | None
    description: str


def _dash_to_none(value: str) -> str | None:
    value = value.strip()
    return None if value in ("", "-") else value


def parse_delegation_entries(lines: Iterable[str]) -> list[DelegationEntry]:
    """Parse delegation-log lines into entries.

    Handles the current 6-column schema and the legacy 4-column one (no session/zone) so
    a mixed local log still parses; lines with fewer than 4 fields are skipped.
    """
    entries: list[DelegationEntry] = []
    for raw in lines:
        line = raw.rstrip("\n")
        if not line:
            continue
        parts = line.split("\t")
        if len(parts) >= _CURRENT_SCHEMA_COLUMNS:
            ts, sid, subagent, model, zone = parts[0], parts[1], parts[2], parts[3], parts[4]
            description = "\t".join(parts[5:])
        elif len(parts) >= _LEGACY_SCHEMA_COLUMNS:
            # Legacy: timestamp · subagent · model · description (no session / zone).
            ts, sid, subagent, model, zone = parts[0], "-", parts[1], parts[2], "-"
            description = "\t".join(parts[3:])
        else:
            continue
        entries.append(
            DelegationEntry(
                timestamp=ts,
                session_id=_dash_to_none(sid),
                subagent=subagent.strip(),
                model=_dash_to_none(model),
                zone=_dash_to_none(zone),
                description=description.strip(),
            )
        )
    return entries
