#!/usr/bin/env python3
"""The one owner of the package-mode materialization: its format, and whether it is current.

Mode `package` puts **no executable surface** in the consumer repository (ADR 0009, the C77
amendment). Exactly one thing is still written there: the guardrail files the consumer's
``AGENTS.md`` ``@``-imports, because that import sits in a committed, hand-owned document and
the only path from it into the installed package carries the venv's Python version.

That copy is the consumer's *rules*, not its plumbing, so it must not go quietly stale. Two
different callers need the same answer and must not disagree about it:

- ``bin/sync.py`` **writes** the file (and ``sync --check`` / ``verify`` compare what it would
  write against what is on disk — the CI half of the guarantee);
- ``hooks/hook_core.py`` **reads** it at SessionStart and says so when the installed standard
  has moved past it — the interactive half, which is the window a CI gate cannot cover: a pin
  bump installs new hooks the moment the dependency resolves, while the guardrails in the
  repository are still the previous release's until someone runs ``akmon sync``.

Two owners of one file format is exactly the split this repository has paid for before (see
``meta/design/packaging/mount-resolution-owner.md``), so the banner rule and the comparison
live here and the callers hold no copy of either.

Stdlib-only and venv-free by contract, like every module in ``common/``.
"""

from __future__ import annotations

from pathlib import Path

from common.project_root import aitna_root, aitna_root_name

# Stable substring used to recognise a generated file regardless of the configured root —
# verify/sync look for this prefix, not the full banner (which embeds the root path).
GENERATED_MARKER = "Generated by "


def generated_banner() -> str:
    """The do-not-edit banner; tracks the configured root so it never drifts from real paths."""
    return f"{GENERATED_MARKER}{aitna_root_name()}/akmon/bin/sync.py. Do not edit this file by hand."


def materialized_markdown(source_text: str) -> str:
    """``source_text`` with the generated-pointer banner inserted as an HTML comment
    (matching the convention the other generated ``.md`` pointers already use), right after
    a leading top-level heading when present, else at the very top.
    """
    banner_line = f"<!-- {generated_banner()} -->"
    lines = source_text.splitlines(keepends=True)
    if lines and lines[0].lstrip().startswith("#"):
        return lines[0] + banner_line + "\n\n" + "".join(lines[1:])
    return banner_line + "\n\n" + source_text


def materialized_guardrails_dir(project_root: Path) -> Path:
    """Where package mode writes the imported guardrails."""
    return aitna_root(project_root) / ".akmon" / "guardrails"


def stale_guardrails(project_root: Path, tree_root: Path) -> list[str]:
    """Materialized guardrail file names whose text is no longer what ``tree_root`` ships.

    ``tree_root`` is the standard tree the caller is actually running from, so the comparison
    is against the code that is executing rather than against a recorded version string: a
    bump that leaves the guardrails untouched must stay silent, and a hand-edit of the copy
    must not.

    Empty for a project with no materialization at all — every mounted-mode project, and a
    package-mode project between ``init`` and its first ``sync``. Directory scan rather than a
    re-read of ``AGENTS.md``'s imports: what is on disk is what the harness will load, and an
    import with no file behind it is a *plan* error ``sync`` and ``verify`` already report.

    Unreadable files count as stale. The caller is a hook that must never raise, and "cannot be
    compared" and "does not match" lead to the same instruction.
    """
    dest = materialized_guardrails_dir(project_root)
    if not dest.is_dir():
        return []
    stale: list[str] = []
    for path in sorted(dest.glob("*.md")):
        source = tree_root / "guardrails" / path.name
        try:
            if not source.is_file():
                stale.append(path.name)
            elif path.read_text(encoding="utf-8") != materialized_markdown(
                source.read_text(encoding="utf-8")
            ):
                stale.append(path.name)
        except OSError:
            stale.append(path.name)
    return stale
